//! Encoder GEMM kernel probe — parity/mulmat_q8_bert_ref.bin, generated by
//! parity/ref_mulmat_q8_dump.c through the reference's *production* mul_mat in
//! the shapes the BERT/T5-encoder graphs use.
//!
//! This is the test that decides whether an encoder run can be bit-exact or
//! only tail-comparable (see bert_e2e.rs / t5_e2e.rs's headers):
//!
//!   * Q8_0 weights (bge-m3): `llamafile_sgemm` *accepts* the call — the
//!     activation type of a Q8_0 weight is Q8_0 again, so `Btype == Atype`
//!     (sgemm.cpp:4041-4046) and the GEMM goes through tinyBLAS_Q0_AVX even for
//!     T >= 2. Its 8-lane f32 accumulator + final hsum is structurally the same
//!     as the reference's AVX2 `ggml_vec_dot_q8_0_q8_0`, and this test asserts
//!     the port reproduces it bit-for-bit in every encoder shape (k=1024/4096,
//!     rows=1024/4096, cols = 1..64).
//!   * F32 (the attention kq / kqv matmuls): tinyBLAS<16,__m512> runs whenever
//!     `m % 4 == 0 && k % 16 == 0 && n >= 2` (sgemm.cpp:494-532 bails
//!     otherwise). Where it does NOT run the reference uses `ggml_vec_dot_f32`,
//!     which this port models only for `k % 64 == 0`. The test asserts
//!     bit-exactness in exactly that "vec_dot-eligible" region and records (does
//!     not fail on) the 1e-5..2.4e-4 gap outside it.
//!
//! Run: `cargo test -p llama --release --test encode_gemm_probe -- --nocapture`

use ggml::types::GgmlType;
use ggml::{Context, Graph};
const REF: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/mulmat_q8_bert_ref.bin"
);

struct Sec {
    ty: GgmlType,
    n: usize,
    rows: usize,
    cols: usize,
    xq: Vec<u8>,
    y: Vec<f32>,
    dst: Vec<f32>,
}

fn parse(bytes: &[u8]) -> Vec<Sec> {
    let mut out = Vec::new();
    let mut off = 0usize;
    let u32at = |o: usize| u32::from_le_bytes(bytes[o..o + 4].try_into().unwrap());
    while off + 4 <= bytes.len() {
        let magic = u32at(off);
        if magic == 0xFFFF_FFFF {
            break;
        }
        let ty = match magic {
            0x3851_4D56 => GgmlType::Q8_0, // 'VMQ8'
            0x3233_4D56 => GgmlType::F32,  // 'VM32'
            other => panic!("bad section magic {other:#x} at {off}"),
        };
        let n = u32at(off + 4) as usize;
        let rows = u32at(off + 8) as usize;
        let cols = u32at(off + 12) as usize;
        off += 16;
        let xbytes = ty.row_size(n * rows);
        let xq = bytes[off..off + xbytes].to_vec();
        off += xbytes;
        let y: Vec<f32> = bytes[off..off + 4 * n * cols]
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        off += 4 * n * cols;
        let dst: Vec<f32> = bytes[off..off + 4 * rows * cols]
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        off += 4 * rows * cols;
        out.push(Sec {
            ty,
            n,
            rows,
            cols,
            xq,
            y,
            dst,
        });
    }
    out
}

/// `llamafile_sgemm` eligibility for the F32 case: `tinyBLAS::matmul` returns
/// false unless `k % KN == 0` and `m % 4 == 0` (sgemm.cpp:494-532), and
/// `llamafile_sgemm` itself bails for `n < 2` (sgemm.cpp:3815-3819). KN is the
/// AVX512 vector width, 16 (the reference build is AVX512).
fn tinyblas_f32_eligible(k: usize, m: usize, cols: usize) -> bool {
    cols >= 2 && k % 16 == 0 && m % 4 == 0
}

/// The port's f32 vec_dot models the reference's AVX512 F32Cx16 kernel
/// (STEP 64, ARR 4; vec_dot.rs `vec_dot_f32_c`), so it is bit-exact exactly
/// when the reduction length is a multiple of 64.
fn port_f32_exact(k: usize, m: usize, cols: usize) -> bool {
    !tinyblas_f32_eligible(k, m, cols) && k % 64 == 0
}

/// One `mul_mat(weights [n, rows], activations [n, cols])` through the port's
/// real dispatch (a 1-layer graph, exactly like the production path).
fn mul_mat(s: &Sec) -> Vec<f32> {
    let mut gctx = Context::new();
    let a = gctx.new_tensor_2d(s.ty, s.n as i64, s.rows as i64);
    let b = gctx.new_tensor_2d(GgmlType::F32, s.n as i64, s.cols as i64);
    gctx.arena_resize_tensor(a);
    gctx.arena_resize_tensor(b);
    gctx.data_bytes_mut(a).unwrap().copy_from_slice(&s.xq);
    gctx.data_bytes_mut(b)
        .unwrap()
        .copy_from_slice(bytemuck::cast_slice(&s.y));
    let d = gctx.mul_mat(a, b);
    let mut g = Graph::new(8);
    g.build_forward(&gctx, d);
    ggml::compute::graph_compute(&mut gctx, &mut g, 8);
    let v: &[f32] = bytemuck::cast_slice(gctx.data_bytes(d).unwrap());
    v[..s.rows * s.cols].to_vec()
}

#[test]
fn encoder_gemm_shapes_vs_reference() {
    let Ok(bytes) = std::fs::read(REF) else {
        eprintln!("SKIP: {REF} missing (run parity/ref_mulmat_q8_dump)");
        return;
    };
    let secs = parse(&bytes);
    println!("{} sections", secs.len());
    let mut q8_bad = Vec::new();
    let mut f32_bad = Vec::new();
    let mut f32_gap = 0f32;
    for s in &secs {
        let ours = mul_mat(s);
        let diffs = ours
            .iter()
            .zip(&s.dst)
            .filter(|(a, b)| a.to_bits() != b.to_bits())
            .count();
        let max_abs = ours
            .iter()
            .zip(&s.dst)
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max);
        let tag = format!("[k={} rows={} cols={}]", s.n, s.rows, s.cols);
        match s.ty {
            GgmlType::Q8_0 => {
                println!(
                    "  Q8_0 {tag}: {}/{} bit-exact, max|d|={max_abs:.3e}",
                    ours.len() - diffs,
                    ours.len()
                );
                if diffs != 0 {
                    q8_bad.push(tag);
                }
            }
            GgmlType::F32 => {
                let exact = port_f32_exact(s.n, s.rows, s.cols);
                let tb = tinyblas_f32_eligible(s.n, s.rows, s.cols);
                println!(
                    "  F32  {tag}: {}/{} bit-exact, max|d|={max_abs:.3e}                      (tinyBLAS-eligible={tb}, port-exact-expected={exact})",
                    ours.len() - diffs,
                    ours.len()
                );
                if exact && diffs != 0 {
                    f32_bad.push(tag.clone());
                }
                if !exact {
                    f32_gap = f32_gap.max(max_abs);
                    // the deviating shapes must stay at kernel-structure level
                    assert!(
                        max_abs < 1e-3,
                        "F32 {tag}: max|d|={max_abs:.3e} — structural regression"
                    );
                }
            }
            other => panic!("unexpected type {other:?}"),
        }
    }
    assert!(
        q8_bad.is_empty(),
        "Q8_0 GEMM shapes not bit-exact: {q8_bad:?}"
    );
    assert!(
        f32_bad.is_empty(),
        "F32 vec_dot-eligible shapes not bit-exact: {f32_bad:?}"
    );
    println!("F32 non-eligible worst |d| = {f32_gap:.3e} (tinyBLAS / f32 tail gap, see PARITY.md)");
}
