//! mtmd_audio_parity.rs — bit-exact parity of the mtmd-audio.cpp port
//! (crates/llama/src/mtmd_audio.rs) against the pinned reference
//! (parity/mtmd_audio_ref.bin, regenerated by parity/gen_mtmd_audio_ref.sh).
//!
//! The reference probe compiles tools/mtmd/mtmd-audio.cpp from the pinned
//! tree and runs every preprocessor on the same fixture PCM
//! (parity/mtmd-fixture-audio.f32); every output f32 must match bit-for-bit
//! (f32::to_bits), which pins the FFT, the mel filterbank, the padding /
//! normalization variants and the streaming ISTFT.
//!
//! The fixture WAV (mtmd-fixture-audio.wav) additionally checks the port's
//! WAV reader (mtmd::audio_from_wav_bytes) against the exact f32 the
//! reference's miniaudio path decodes the same file to.

use llama::mtmd::audio_from_wav_bytes;
use llama::mtmd_audio::*;

fn fixture_dir() -> String {
    option_env!("MTMD_AUDIO_FIXTURE_DIR")
        .map(|s| s.to_string())
        .unwrap_or_else(|| "../../parity".to_string())
}

/// the deterministic parakeet filterbank/window (ref_mtmd_audio_dump.cpp)
fn parakeet_hparams() -> AudioHparams {
    let n_mel = 64i32;
    let n_fft = 512i32;
    let n_fft_bins = (n_fft / 2 + 1) as usize;
    let mut hp = AudioHparams {
        n_mel_bins: n_mel,
        audio_sample_rate: 16000,
        audio_n_fft: n_fft,
        audio_window_len: 400,
        audio_hop_len: 160,
        ..AudioHparams::default()
    };
    hp.mel_filters = Vec::with_capacity(n_mel as usize * n_fft_bins);
    for i in 0..(n_mel as usize * n_fft_bins) {
        hp.mel_filters
            .push(((((i * 37) % 97) as f64) / 97.0) as f32);
    }
    hp.window = Vec::with_capacity(400);
    for i in 0..400 {
        // 0.5f * (1.0f - cosf((float)(2.0 * M_PI * i / 400.0))) — f32 math
        let arg = (2.0 * std::f64::consts::PI * i as f64 / 400.0) as f32;
        hp.window.push(0.5f32 * (1.0f32 - arg.cos()));
    }
    hp
}

struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn i64(&mut self) -> i64 {
        let b = &self.data[self.pos..self.pos + 8];
        self.pos += 8;
        i64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]])
    }
    fn f32(&mut self) -> f32 {
        let b = &self.data[self.pos..self.pos + 4];
        self.pos += 4;
        f32::from_le_bytes([b[0], b[1], b[2], b[3]])
    }
    fn mels(&mut self) -> Vec<AudioMel> {
        let n_chunks = self.i64();
        let mut out = Vec::new();
        for _ in 0..n_chunks {
            let n_len = self.i64();
            let n_len_org = self.i64();
            let n_mel = self.i64();
            let data = (0..(n_len * n_mel) as usize).map(|_| self.f32()).collect();
            out.push(AudioMel {
                n_len,
                n_len_org,
                n_mel,
                data,
            });
        }
        out
    }
}

fn assert_mels_bit_equal(name: &str, got: &[AudioMel], exp: &[AudioMel]) {
    assert_eq!(got.len(), exp.len(), "{name}: chunk count");
    for (i, (g, e)) in got.iter().zip(exp.iter()).enumerate() {
        assert_eq!(g.n_len, e.n_len, "{name}[{i}]: n_len");
        assert_eq!(g.n_len_org, e.n_len_org, "{name}[{i}]: n_len_org");
        assert_eq!(g.n_mel, e.n_mel, "{name}[{i}]: n_mel");
        assert_eq!(g.data.len(), e.data.len(), "{name}[{i}]: data len");
        for (j, (a, b)) in g.data.iter().zip(e.data.iter()).enumerate() {
            assert_eq!(
                a.to_bits(),
                b.to_bits(),
                "{name}[{i}].data[{j}] differs: {a} vs {b}"
            );
        }
    }
}

#[test]
fn mtmd_audio_preprocessors_bit_exact() {
    let dir = fixture_dir();
    let ref_bytes = std::fs::read(format!("{dir}/mtmd_audio_ref.bin"))
        .expect("parity/mtmd_audio_ref.bin (run parity/gen_mtmd_audio_ref.sh)");
    let samples: Vec<f32> = std::fs::read(format!("{dir}/mtmd-fixture-audio.f32"))
        .expect("parity/mtmd-fixture-audio.f32")
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    assert!(!samples.is_empty());

    // the port's WAV reader decodes the fixture WAV to the same PCM
    let wav = std::fs::read(format!("{dir}/mtmd-fixture-audio.wav")).unwrap();
    let decoded = audio_from_wav_bytes(&wav, 16000).expect("wav decode");
    assert_eq!(decoded.len(), samples.len(), "wav sample count");
    for (i, (a, b)) in decoded.iter().zip(samples.iter()).enumerate() {
        assert_eq!(
            a.to_bits(),
            b.to_bits(),
            "wav-decoded sample {i}: {a} vs {b}"
        );
    }

    let mut r = Reader {
        data: &ref_bytes,
        pos: 0,
    };

    // whisper
    {
        assert_eq!(r.i64(), 1, "reference whisper ok");
        let exp = r.mels();
        let mut p = WhisperPreproc::new(AudioHparams {
            n_mel_bins: 128,
            audio_sample_rate: 16000,
            audio_n_fft: 400,
            audio_window_len: 400,
            audio_hop_len: 160,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("whisper", &got, &exp);
    }
    // qwen3a
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = Qwen3aPreproc::new(AudioHparams {
            n_mel_bins: 128,
            audio_sample_rate: 16000,
            audio_n_fft: 512,
            audio_window_len: 400,
            audio_hop_len: 160,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("qwen3a", &got, &exp);
    }
    // dots3note
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = Dots3NotePreproc::new(AudioHparams {
            n_mel_bins: 128,
            audio_sample_rate: 16000,
            audio_n_fft: 400,
            audio_window_len: 400,
            audio_hop_len: 160,
            audio_chunk_len: 60,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("dots3note", &got, &exp);
    }
    // mimo_audio
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = MimoAudioPreproc::new(AudioHparams {
            n_mel_bins: 40,
            audio_sample_rate: 24000,
            audio_n_fft: 960,
            audio_window_len: 960,
            audio_hop_len: 240,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("mimo_audio", &got, &exp);
    }
    // qwen3tts_spk
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = Qwen3TtsSpkPreproc::new(AudioHparams {
            n_mel_bins: 80,
            audio_sample_rate: 24000,
            audio_n_fft: 1024,
            audio_window_len: 1024,
            audio_hop_len: 256,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("qwen3tts_spk", &got, &exp);
    }
    // conformer
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = ConformerPreproc::new(AudioHparams {
            n_mel_bins: 80,
            audio_sample_rate: 16000,
            audio_n_fft: 512,
            audio_window_len: 400,
            audio_hop_len: 160,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("conformer", &got, &exp);
    }
    // granite_speech
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = GraniteSpeechPreproc::new(AudioHparams {
            n_mel_bins: 80,
            audio_sample_rate: 16000,
            audio_n_fft: 512,
            audio_window_len: 400,
            audio_hop_len: 160,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("granite_speech", &got, &exp);
    }
    // gemma4a
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = Gemma4aPreproc::new(AudioHparams {
            n_mel_bins: 128,
            audio_sample_rate: 16000,
            audio_n_fft: 1024,
            audio_window_len: 640,
            audio_hop_len: 320,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("gemma4a", &got, &exp);
    }
    // gemma4ua
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = Gemma4uaPreproc::new(AudioHparams {
            n_mel_bins: 640,
            audio_sample_rate: 16000,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("gemma4ua", &got, &exp);
    }
    // parakeet
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = ParakeetPreproc::new(parakeet_hparams());
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("parakeet", &got, &exp);
    }
    // pockettts
    {
        assert_eq!(r.i64(), 1);
        let exp = r.mels();
        let mut p = PocketTtsPreproc::new(AudioHparams {
            audio_sample_rate: 24000,
            mimi_downsample: 8,
            ..AudioHparams::default()
        });
        p.initialize();
        let mut got = Vec::new();
        assert!(p.preprocess(&samples, &mut got));
        assert_mels_bit_equal("pockettts", &got, &exp);
    }

    // streaming ISTFT
    {
        let n = r.i64() as usize;
        let exp: Vec<f32> = (0..n).map(|_| r.f32()).collect();
        let mut istft = StreamingIstdft::new(256, 64);
        let mut got: Vec<f32> = Vec::new();
        for frame in 0..16i32 {
            let mut spec = vec![0.0f32; (256 / 2 + 1) * 2];
            for j in 0..(256 / 2 + 1) {
                let mag = 0.5 * (1.0 + (0.37 * j as f64 + 0.11 * frame as f64).sin());
                let ph = 0.9 * j as f64 - 1.3 * frame as f64 + 0.5 * (frame as f64 * 0.7).sin();
                spec[2 * j] = (mag * ph.cos()) as f32;
                spec[2 * j + 1] = (mag * ph.sin()) as f32;
            }
            got.extend(istft.process_frame(&spec));
        }
        got.extend(istft.flush());
        assert_eq!(got.len(), exp.len(), "istft sample count");
        for (i, (a, b)) in got.iter().zip(exp.iter()).enumerate() {
            assert_eq!(a.to_bits(), b.to_bits(), "istft sample {i}: {a} vs {b}");
        }
    }

    assert_eq!(r.pos, ref_bytes.len(), "all reference bytes consumed");
}
