//! nextn_crop_dump.rs — the f0c41e016 crop-timing acceptance (M-domain task
//! 3): one mimo2 trunk prefill in the draft-mtp **target's** unmasked-nextn
//! configuration (`set_embeddings_nextn(true, false)`, speculative.cpp:1420)
//! over a PARTIAL-output batch (only the last row logits=1), with the
//! DECDMP1 node stream bit-compared against the NEW reference probe
//! `parity/ref_nextn_crop_dump.c` (named-node pairing) over
//! `parity/mimo2/nextn_crop_nodes_ref.bin`, regenerated by
//! `parity/nextn_crop_parity.sh`.
//!
//! mimo2 is the arch whose unconditional `t_h_nextn` emission f0c41e016
//! itself fixed (mimo2.cpp:236-243: "pre-norm state for MTP; set even when
//! extraction is off"), and the unmasked + partial-outputs combination is
//! the only one where the crop helpers change the graph: crop_before_
//! nextn's early narrow is skipped, t_h_nextn keeps every row and
//! crop_after_nextn's gather lands between the capture and the head.
//!
//! The mimo2 synth is tests/mtp2_e2e.rs's fixed-name writer product
//! (/tmp/mtp2/mimo2-synth-mtp.gguf) — this test early-returns when the
//! generator has not run (the parity script drives both sides).

use std::io::Write as _;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::{Arc, Mutex, OnceLock};

use ggml::compute::{set_eval_callback, EvalNode};
use ggml::types::GgmlType;
use ggml::{Context, Gguf};
use llama::batch::LlamaBatch;
use llama::context::{DecodeContext, ForwardWeights};
use llama::graph::AttnParams;
use llama::graph_arch;
use llama::hparams::LlamaHparams;
use llama::kv_cache::SwaCacheSpec;
use llama::model::{load_model, LlamaModel, LayerTensors};
use llama::vocab::Vocab;
use memmap2::Mmap;

const SYNTH: &str = "/tmp/mtp2/mimo2-synth-mtp.gguf";
const REF_NODES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../parity/mimo2/nextn_crop_nodes_ref.bin");
const OUT_NODES: &str = "/tmp/closm-mimo2-nextn-crop-port.bin";
/// nodes at/above this element count carry no payload (2^19, the probe rule)
const ELEM_CAP: u64 = 1 << 19;

struct DumpState {
    out: Vec<u8>,
    nodes: u32,
}

static DUMP: OnceLock<Mutex<Option<DumpState>>> = OnceLock::new();
static ACTIVE: AtomicU32 = AtomicU32::new(0);

fn op_desc(op: ggml::GgmlOp) -> &'static str {
    use ggml::GgmlOp::*;
    match op {
        None => "NONE",
        Dup => "DUP",
        Add => "ADD",
        Mul => "MUL",
        Div => "DIV",
        Sub => "SUB",
        Norm => "NORM",
        SquaredMulMat => "MUL_MAT_SQ",
        MulMat => "MUL_MAT",
        Scale => "SCALE",
        Cpy => "CPY",
        Reshape => "RESHAPE",
        View => "VIEW",
        Permute => "PERMUTE",
        Transpose => "TRANSPOSE",
        GetRows => "GET_ROWS",
        DiagMaskInf => "DIAG_MASK_INF",
        SoftMax => "SOFT_MAX",
        RoPE => "ROPE",
        RoPEBack => "ROPE_BACK",
        MulMatId => "MUL_MAT_ID",
        Argsort => "ARGSORT",
        ArgMax => "ARGMAX",
        Repeat => "REPEAT",
        Concat => "CONCAT",
        Silu => "SILU",
        SumRows => "SUM_ROWS",
        MulView => "MUL_VIEW",
        SetRows => "SET_ROWS",
        FlashAttnExt => "FLASH_ATTN_EXT",
        AddId => "ADD_ID",
        Glu => "GLU",
        SsmConv => "SSM_CONV",
        SsmScan => "SSM_SCAN",
        Clamp => "CLAMP",
        Gdn => "GATED_DELTA_NET",
        Im2col => "IM2COL",
        Upscale => "UPSCALE",
        Fill => "FILL",
        LightningIndexer => "LIGHTNING_INDEXER",
        TopK => "TOP_K",
        Sqrt => "SQRT",
        Sin => "SIN",
        Cos => "COS",
        Sqr => "SQR",
        Mean => "MEAN",
        PadReflect1d => "PAD_REFLECT_1D",
        Dsv4HcComb => "dsv4_hc_comb(mixes, scale, base)",
        Dsv4HcPre => "dsv4_hc_pre(x, weights)",
        Dsv4HcPreGated => "dsv4_hc_pre_gated(x, gate, scale)",
        Dsv4HcPost => "dsv4_hc_post(x, residual, post, comb)",
        Pad => "PAD",
        Pool2d => "POOL_2D",
        Roll => "ROLL",
        Conv2dDirect => "CONV_2D_DIRECT",
        Conv2dDw => "CONV_2D_DW",
        Sum => "SUM",
        Cumsum => "CUMSUM",
        Tri => "TRI",
        Log => "LOG",
        Col2Im1d => "COL2IM_1D",
    }
}

fn type_desc(ty: GgmlType) -> &'static str {
    match ty {
        GgmlType::F32 => "f32",
        GgmlType::F16 => "f16",
        GgmlType::Bf16 => "bf16",
        GgmlType::I64 => "i64",
        GgmlType::I32 => "i32",
        GgmlType::I16 => "i16",
        GgmlType::I8 => "i8",
        _ => "other",
    }
}

fn dump_cb(node: &EvalNode<'_>, ask: bool) -> bool {
    if ask {
        return true;
    }
    let mut guard = DUMP.get().unwrap().lock().unwrap();
    let Some(st) = guard.as_mut() else {
        return true;
    };
    let n: i64 = node.ne.iter().product();
    st.nodes += 1;
    let mut put = |s: &str| {
        let len = s.len().min(255);
        st.out.push(len as u8);
        st.out.extend_from_slice(&s.as_bytes()[..len]);
    };
    put(op_desc(node.op));
    put(node.name);
    put(type_desc(node.ty));
    st.out
        .extend(node.ne.iter().map(|v| v.to_le_bytes()).collect::<Vec<_>>().concat());
    st.out.extend(&(n as u64).to_le_bytes());
    let data = node.data.unwrap_or(&[]);
    if n as u64 >= ELEM_CAP {
        return true;
    }
    if !matches!(node.ty, GgmlType::F32 | GgmlType::F16) {
        st.out.extend(std::iter::repeat(0u8).take(4 * n as usize));
        return true;
    }
    for flat in 0..n as usize {
        let mut rem = flat as i64;
        let mut off = 0usize;
        for d in 0..4 {
            let idx = rem % node.ne[d];
            rem /= node.ne[d];
            off += (idx as u64 * node.nb[d]) as usize;
        }
        let v: f32 = if node.ty == GgmlType::F32 {
            f32::from_le_bytes([data[off], data[off + 1], data[off + 2], data[off + 3]])
        } else {
            half::f16::from_le_bytes([data[off], data[off + 1]]).to_f32()
        };
        st.out.extend_from_slice(&v.to_le_bytes());
    }
    true
}

// ---------------------------------------------------------------------------
// the mimo2 trunk bundle (tests/mtp2_e2e.rs's mimo2 converters)
// ---------------------------------------------------------------------------

fn mimo2_layer(l: &LayerTensors) -> graph_arch::Mimo2LayerWeights {
    graph_arch::Mimo2LayerWeights {
        attn_norm: l.attn_norm.unwrap(),
        wqkv: l.wqkv,
        wqkv_b: l.wqkv_b,
        wq: l.wq,
        wq_b: l.wq_b,
        wk: l.wk,
        wk_b: l.wk_b,
        wv: l.wv,
        wv_b: l.wv_b,
        wo: l.wo.unwrap(),
        attn_sinks: l.attn_sinks,
        ffn_norm: l.ffn_norm.unwrap(),
        ffn_gate: l.ffn_gate,
        ffn_down: l.ffn_down,
        ffn_up: l.ffn_up,
        ffn_gate_inp: l.ffn_gate_inp,
        ffn_exp_probs_b: l.ffn_exp_probs_b,
        ffn_up_exps: l.ffn_up_exps,
        ffn_gate_exps: l.ffn_gate_exps,
        ffn_down_exps: l.ffn_down_exps,
    }
}

fn mimo2_params(hp: &LlamaHparams, n_trunk: usize, attn: AttnParams) -> graph_arch::Mimo2Params {
    graph_arch::Mimo2Params {
        attn,
        norm_rms_eps: hp.f_norm_rms_eps,
        freq_base: vec![hp.rope_freq_base_train; n_trunk],
        freq_scale: vec![1.0; n_trunk],
        v_scale: hp.f_attn_value_scale,
        n_expert: hp.n_expert as i64,
        n_expert_used: hp.n_expert_used(0) as i64,
        expert_weights_scale: hp.expert_weights_scale,
    }
}

fn trunk_driver_of(m: &mut LlamaModel) -> DecodeContext {
    let hp = &m.hparams;
    let n_trunk = hp.n_layer() as usize;
    let rope = hp.rope_runtime();
    let attn = AttnParams {
        n_head: hp.n_head(0) as i64,
        n_head_kv: hp.n_head_kv(0) as i64,
        n_embd_head_k: hp.n_embd_head_k(0) as i64,
        n_embd_head_v: hp.n_embd_head_v(0) as i64,
        n_rot: hp.n_rot(0) as i64,
        rope_mode: hp.rope_type as i32,
        n_ctx_orig: rope.n_ctx_orig_yarn,
        freq_base: hp.rope_freq_base_train,
        freq_scale: rope.freq_scale,
        ext_factor: rope.ext_factor,
        attn_factor: rope.attn_factor,
        beta_fast: rope.beta_fast,
        beta_slow: rope.beta_slow,
        norm_eps: hp.f_norm_rms_eps,
        // the probe's --fa off (the verified baseline)
        use_flash_attn: false,
    };
    let weights = ForwardWeights::Mimo2(
        graph_arch::Mimo2ModelWeights {
            tok_embd: m.tok_embd,
            output_norm: m.output_norm,
            output: m.output,
            layers: m.layers[..n_trunk].iter().map(mimo2_layer).collect(),
        },
        mimo2_params(hp, n_trunk, attn),
    );
    let gctx = std::mem::replace(&mut m.ctx, Context::new());
    DecodeContext::new_with_swa(
        gctx,
        weights,
        attn,
        512,
        8,
        2048,
        SwaCacheSpec::from_hparams(&m.hparams),
    )
}

/// the port side of the crop probe: the partial-output prefill in the
/// unmasked-nextn configuration, node stream to OUT_NODES
#[test]
#[ignore = "manual: writes the DECDMP1 node dump for the crop-timing parity"]
fn nextn_crop_node_dump() {
    let file = std::fs::File::open(SYNTH).expect("open the mimo2 synth (run the mtp2 generator)");
    let mmap = Arc::new(unsafe { Mmap::map(&file).expect("mmap") });
    let gguf = Gguf::from_bytes(mmap.clone()).expect("gguf parse");
    let mut model = load_model(&gguf, mmap.clone()).expect("load model");

    let vocab = Vocab::load(&gguf).expect("vocab");
    let ids = vocab.tokenize("1, 2, 3", true, true);
    let n = ids.len();

    let mut d = trunk_driver_of(&mut model);
    // the draft-mtp target's tap (speculative.cpp:1420) — unmasked
    d.set_embeddings_nextn(true, false);

    DUMP.get_or_init(|| Mutex::new(Some(DumpState { out: Vec::new(), nodes: 0 })));
    {
        let mut guard = DUMP.get().unwrap().lock().unwrap();
        *guard = Some(DumpState { out: Vec::new(), nodes: 0 });
    }
    set_eval_callback(Some(dump_cb));
    ACTIVE.store(1, Ordering::SeqCst);

    // the probe's batch: every token at its own position, only the LAST row
    // an output — build_inp_out_ids goes live and the crop helpers decide
    let mut b = LlamaBatch::default();
    for (i, &id) in ids.iter().enumerate() {
        b.add(id, i as i32, &[0], i + 1 == n);
    }
    let out = d.decode_batch(&b).expect("partial-output prefill");
    assert_eq!(out.n_outputs, 1, "one logits row");
    // the unmasked tap keeps EVERY row (llama-context.cpp:2010-2027)
    assert_eq!(d.get_embeddings_nextn().len(), n * (model.hparams.n_embd as usize));

    ACTIVE.store(0, Ordering::SeqCst);
    set_eval_callback(None);

    let (nodes, body) = {
        let mut guard = DUMP.get().unwrap().lock().unwrap();
        let st = guard.take().unwrap();
        (st.nodes, st.out)
    };
    let mut f = std::fs::File::create(OUT_NODES).expect("create dump");
    f.write_all(b"DECDMP1\0").unwrap();
    f.write_all(&(n as u32).to_le_bytes()).unwrap();
    for &id in &ids {
        f.write_all(&id.to_le_bytes()).unwrap();
    }
    f.write_all(&nodes.to_le_bytes()).unwrap();
    f.write_all(&body).unwrap();
    println!("nextn_crop: {nodes} nodes -> {OUT_NODES}");
}

/// the DEFAULT acceptance: the port node stream vs the stored reference
/// probe's (named-node pairing — both sides carry the same cb names, so the
/// pairing must be total and byte-identical; the port's extra unnamed helper
/// nodes are skipped by the pairing rule exactly like glm5_dump's)
#[test]
fn nextn_crop_nodes_bit_exact_vs_reference() {
    let Ok(ref_bytes) = std::fs::read(REF_NODES) else {
        eprintln!("nextn_crop: no stored reference stream ({REF_NODES}) — run parity/nextn_crop_parity.sh");
        return;
    };
    let Ok(port_bytes) = std::fs::read(OUT_NODES) else {
        eprintln!("nextn_crop: no port dump ({OUT_NODES}) — run the ignored nextn_crop_node_dump cell");
        return;
    };

    // parse both DECDMP1 streams into (name, payload) records
    struct Rec {
        name: String,
        /// ne[4] + n_elems + the payload bytes when under the element cap
        body: Vec<u8>,
        /// payload length (None = over the cap, no payload in the stream)
        payload: Option<usize>,
    }
    impl Rec {
        fn shape_checked(&self) -> Option<&[u8]> {
            self.payload.map(|l| &self.body[self.body.len() - l..])
        }
    }
    let parse = |b: &[u8]| -> (Vec<i32>, Vec<Rec>) {
        assert_eq!(&b[..8], b"DECDMP1\0");
        let rd_u32 = |o: &mut usize| u32::from_le_bytes(b[*o..*o + 4].try_into().unwrap());
        let n_tok = rd_u32(&mut 8) as usize;
        let toks = (0..n_tok)
            .map(|i| i32::from_le_bytes(b[12 + 4 * i..16 + 4 * i].try_into().unwrap()))
            .collect();
        let mut o = 12 + 4 * n_tok;
        let n_nodes = rd_u32(&mut o) as usize;
        o += 4;
        let mut recs = Vec::with_capacity(n_nodes);
        for _ in 0..n_nodes {
            let take_str = |o: &mut usize| -> String {
                let l = b[*o] as usize;
                *o += 1;
                let s = String::from_utf8_lossy(&b[*o..*o + l]).into_owned();
                *o += l;
                s
            };
            let _op = take_str(&mut o);
            let name = take_str(&mut o);
            let _ty = take_str(&mut o);
            let shape_start = o;
            o += 32 + 8;
            let n_elems =
                u64::from_le_bytes(b[o - 8..o].try_into().unwrap());
            // the probe rule: only nodes under the element cap carry a
            // payload (the whole-cache views are skipped on both sides)
            let payload = if n_elems < ELEM_CAP {
                o += 4 * n_elems as usize;
                Some(4 * n_elems as usize)
            } else {
                None
            };
            recs.push(Rec {
                name,
                body: b[shape_start..o].to_vec(),
                payload,
            });
        }
        assert_eq!(
            o,
            b.len(),
            "the DECDMP1 walk must consume the stream (walked to {o}, file {})",
            b.len()
        );
        (toks, recs)
    };
    let (toks_r, recs_r) = parse(&ref_bytes);
    let (toks_p, recs_p) = parse(&port_bytes);
    assert_eq!(toks_r, toks_p, "the tokenized prompt differs");
    assert!(!recs_r.is_empty() && !recs_p.is_empty(), "streams present");

    // named-node pairing (glm5_dump's rule): every node carrying a REAL
    // graph name on the port side must exist on the reference side with the
    // byte-identical shape+payload — ggml's auto names (" (view)",
    // "node_N", "x (reshaped)") pair with their parent's value region, the
    // pure-named nodes cover them
    fn payload_of(r: &Rec) -> Option<&[u8]> {
        // the payload follows the 32-byte shape + 8-byte count when under
        // the element cap; parse kept shape+payload together
        r.shape_checked()
    }
    let mut ridx: std::collections::HashMap<String, Vec<usize>> = Default::default();
    for (i, r) in recs_r.iter().enumerate() {
        if is_graph_name(&r.name) {
            ridx.entry(r.name.clone()).or_default().push(i);
        }
    }
    assert!(!ridx.is_empty(), "the reference stream carries graph names");
    let mut seen: std::collections::HashMap<String, usize> = Default::default();
    let mut compared = 0usize;
    for r in recs_p.iter() {
        if !is_graph_name(&r.name) {
            continue;
        }
        // the port always names + forwards the layer-input tap
        // (mimo2.cpp:237-243 names it only under extract_final_inp, which
        // this probe leaves off — the tap is not read here)
        if r.name.starts_with("layer_inp-") {
            continue;
        }
        let occ = seen.entry(r.name.clone()).or_insert(0);
        let Some(ixs) = ridx.get(&r.name) else {
            panic!("node {:?} has no reference counterpart", r.name);
        };
        assert!(
            *occ < ixs.len(),
            "node {:?}: more port occurrences than reference",
            r.name
        );
        let rnode = &recs_r[ixs[*occ]];
        *occ += 1;
        assert_eq!(
            payload_of(rnode).map(|p| p.len()),
            payload_of(r).map(|p| p.len()),
            "node {:?} payload length",
            r.name
        );
        if let (Some(a), Some(b)) = (payload_of(rnode), payload_of(r)) {
            assert_eq!(a, b, "node {:?} payload bits", r.name);
        }
        compared += 1;
    }
    println!(
        "nextn_crop: {compared} named nodes bit-identical (ref stream {} nodes, port {} nodes)",
        recs_r.len(),
        recs_p.len()
    );
}

/// glm5_dump's rule — a "real" graph name is a cb-set name, not ggml's auto
/// names
fn is_graph_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with(' ')
        && !name.starts_with("node_")
        && !name.contains(" (")
}
