//! sampler_dry_parity.rs — replays `parity/sampler_dry_ref.txt` (generated by
//! `parity/gen_sampler_dry_ref.sh` from the pinned reference build bd4f514db1)
//! against the port's DRY / adaptive-p / infill samplers and the
//! `SamplingContext` chain construction.
//!
//! Every fixture line is produced by the reference `libllama.so` +
//! `libllama-common.so` driving `llama_sampler_init_dry` /
//! `llama_sampler_init_adaptive_p` / `llama_sampler_init_infill` /
//! `common_sampler_init` on the qwen2 vocab GGUF; the test rebuilds the same
//! inputs from the same GGUF through the port's vocab and compares the
//! outputs bit-for-bit (f32 bit patterns for logits/probs, exact token ids
//! for sampled streams, exact chain-name sequences for chain construction).

use llama::sampling::{
    self as smpl, CommonSamplerType, Sampler, SamplingContext, SamplingParams, TokenData,
    TokenDataArray,
};
use llama::vocab::Vocab;

const VOCAB_PATH: &str = "/home/jeffrey/llm/llama.cpp-pinned/models/ggml-vocab-qwen2.gguf";
const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/sampler_dry_ref.txt"
);

fn fixture_lines() -> Vec<String> {
    let text = match std::fs::read_to_string(FIXTURE) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("SKIP: cannot read {FIXTURE}: {e}");
            return Vec::new();
        }
    };
    text.lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect()
}

fn parse_ids(s: &str) -> Vec<i32> {
    s.split(',').filter_map(|t| t.trim().parse().ok()).collect()
}

/// the shared repetitive stream: "Hello world, " x6 tokenized exactly like
/// the probe (add_special=false, parse_special=false)
fn rep_stream(vocab: &Vocab) -> Vec<i32> {
    let mut t = Vec::new();
    for _ in 0..6 {
        t.extend(vocab.tokenize_bytes(b"Hello world, ", false, false));
    }
    t
}

#[test]
fn dry_adaptive_infill_parity() {
    let lines = fixture_lines();
    if lines.is_empty() {
        return;
    }

    let gguf = match ggml::Gguf::open(VOCAB_PATH) {
        Ok(g) => g,
        Err(e) => {
            eprintln!("SKIP: cannot open {VOCAB_PATH}: {e}");
            return;
        }
    };
    let vocab = Vocab::load(&gguf).expect("vocab");
    let n_vocab = vocab.n_tokens() as usize;

    let get =
        |prefix: &str| -> Option<String> { lines.iter().find(|l| l.starts_with(prefix)).cloned() };

    // ------------------------------------------------------------------
    // CHAIN construction — common_sampler_init (defaults + custom order)
    // ------------------------------------------------------------------
    let chain_names = |ctx: &SamplingContext| -> String {
        let mut s = String::new();
        for i in 0..ctx.chain.n() {
            s.push('>');
            s.push_str(ctx.chain.get(i).unwrap().name());
        }
        s
    };

    {
        // DEFAULT: common_params_sampling defaults — the "?dry" empty sampler
        // sits at position 2 exactly like the reference
        let ctx = SamplingContext::new_with_vocab(
            n_vocab as i32,
            Some(&vocab),
            SamplingParams::default(),
        );
        let expect = get("CHAIN DEFAULT").unwrap();
        assert_eq!(format!("CHAIN DEFAULT{}", chain_names(&ctx)), expect);
        // the port's default chain *definition* matches the C's
        assert_eq!(
            SamplingParams::default().samplers,
            CommonSamplerType::default_chain()
        );
    }
    {
        let mut p = SamplingParams::default();
        p.samplers = smpl::common_sampler_types_from_names(&[
            "dry".into(),
            "top_k".into(),
            "top_p".into(),
            "temperature".into(),
        ]);
        let ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        assert_eq!(
            format!("CHAIN NAMES{}", chain_names(&ctx)),
            get("CHAIN NAMES").unwrap()
        );

        let mut p = SamplingParams::default();
        p.samplers = smpl::common_sampler_types_from_chars("dkpt");
        let ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        assert_eq!(
            format!("CHAIN CHARS{}", chain_names(&ctx)),
            get("CHAIN CHARS").unwrap()
        );
    }
    {
        // adaptive-p is appended at the very end, replacing dist
        let mut p = SamplingParams::default();
        p.samplers = smpl::common_sampler_types_from_names(&["top_k".into(), "adaptive_p".into()]);
        let ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        assert_eq!(
            format!("CHAIN ADAPTIVE{}", chain_names(&ctx)),
            get("CHAIN ADAPTIVE").unwrap()
        );
    }
    {
        // dry disabled / enabled at default chain position 2
        let p = SamplingParams::default(); // dry_multiplier = 0
        let ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        assert_eq!(
            format!("CHAIN DRYOFF{}", chain_names(&ctx)),
            get("CHAIN DRYOFF").unwrap()
        );

        let mut p = SamplingParams::default();
        p.dry_multiplier = 0.8;
        let ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        assert_eq!(
            format!("CHAIN DRYON{}", chain_names(&ctx)),
            get("CHAIN DRYON").unwrap()
        );
    }

    // ------------------------------------------------------------------
    // DRY apply fixtures
    // ------------------------------------------------------------------
    let rep = rep_stream(&vocab);
    assert_eq!(
        format!(
            "DRY IDS REP{}",
            rep.iter().map(|t| format!(",{t}")).collect::<String>()
        ),
        get("DRY IDS REP").unwrap(),
        "tokenizer drift: the repeated stream differs from the reference"
    );

    // candidates: distinct repeated tokens (first-appearance order) with
    // hand-set descending logits, then fixed filler ids — same recipe as the
    // probe
    let mut cands: Vec<(i32, f32)> = Vec::new();
    {
        let mut uniq: Vec<i32> = Vec::new();
        for &t in &rep {
            if !uniq.contains(&t) {
                uniq.push(t);
            }
        }
        let mut lg = 1.5f32;
        for t in uniq {
            lg -= 0.25;
            cands.push((t, lg));
        }
        cands.push((5, 0.75));
        cands.push((6, 0.5));
        cands.push((7, 0.25));
    }

    let dry_case = |label: &str,
                    mult: f32,
                    base: f32,
                    allowed: i32,
                    last_n: i32,
                    breakers: &[&str],
                    stream: &[i32]| {
        let brk: Vec<String> = breakers.iter().map(|s| s.to_string()).collect();
        let mut s = smpl::init_dry(Some(&vocab), mult, base, allowed, last_n, &brk);

        let accept_line = format!(
            "{label} ACCEPT{}",
            stream.iter().map(|t| format!(",{t}")).collect::<String>()
        );
        assert_eq!(
            accept_line,
            get(&format!("{label} ACCEPT")).unwrap(),
            "{label} stream"
        );

        for &t in stream {
            s.accept(t);
        }

        let mut cur = TokenDataArray {
            data: cands
                .iter()
                .map(|&(id, l)| TokenData {
                    id,
                    logit: l,
                    p: 0.0,
                })
                .collect(),
            size: cands.len(),
            selected: -1,
            sorted: false,
        };
        s.apply(&mut cur);

        let mut out = format!("{label} APPLY");
        for d in cur.data[..cur.size].iter() {
            out.push_str(&format!(" {}={:08x}", d.id, d.logit.to_bits()));
        }
        assert_eq!(
            out,
            get(&format!("{label} APPLY")).unwrap(),
            "{label} apply"
        );
    };

    let first12: Vec<i32> = rep[..12].to_vec();

    dry_case("DRY1", 0.8, 1.75, 2, 64, &["\n", ":", "\"", "*"], &first12);
    dry_case("DRY2", 0.8, 1.75, 2, 64, &[], &first12);
    dry_case("DRY3", 0.8, 1.75, 10, 64, &["\n"], &first12);
    dry_case("DRY4", 0.8, 1.75, 2, 4, &["\n"], &first12);

    // DRY5: newline breakers interleaved (last token is a breaker -> early out)
    {
        let nl = vocab.tokenize_bytes(b"\n", false, false);
        let mut stream = Vec::new();
        for _ in 0..4 {
            stream.extend_from_slice(&rep[..4]);
            if !nl.is_empty() {
                stream.push(nl[0]);
            }
        }
        dry_case("DRY5", 0.8, 1.75, 2, 64, &["\n"], &stream);
    }

    // DRY6: huge base exercises the max_exponent clamp
    dry_case("DRY6", 1.5, 3.0e6, 1, 64, &["\n"], &first12);

    // DRY7: a breaker token inside the window cuts rep_limit
    {
        let nl = vocab.tokenize_bytes(b"\n", false, false);
        let mut stream = first12.clone();
        stream.push(nl[0]);
        stream.extend_from_slice(&rep[..4]);
        dry_case("DRY7", 0.8, 1.75, 2, 64, &["\n"], &stream);
    }

    // DRY8: a multi-token breaker ("Hello\n" = head + tail) matched via the
    // processed-breaker tail comparison
    {
        let brk = vocab.tokenize_bytes(b"Hello\n", false, false);
        let brk_line = format!(
            "DRY8 BREAKERS{}",
            brk.iter().map(|t| format!(",{t}")).collect::<String>()
        );
        assert_eq!(brk_line, get("DRY8 BREAKERS").unwrap());

        let mut stream = first12.clone();
        stream.extend_from_slice(&brk);
        stream.extend_from_slice(&rep[..4]);
        dry_case("DRY8", 0.8, 1.75, 2, 64, &["Hello\n"], &stream);
    }

    // DRY9: the server-parity scenario — the repetitive cat/mat prompt plus
    // the first 7 generated tokens; the " mat" candidate must receive the
    // reference's exact penalty (bits compared by dry_case)
    {
        let mut stream = vocab.tokenize_bytes(
            b"the cat sat on the mat the cat sat on the mat the cat sat on the mat the cat sat on",
            false,
            false,
        );
        stream.extend_from_slice(&[264, 5517, 279, 8251, 7578, 389, 264]);
        let cands9: Vec<(i32, f32)> = vec![
            (5517, 10.0),
            (61056, 2.0),
            (279, 1.0),
            (271, 0.5),
            (198, 0.3),
            (8251, 0.0),
        ];
        // reuse dry_case's candidate list by temporarily swapping — simplest:
        // inline the same procedure with cands9
        let brk: Vec<String> = vec!["\n".into(), ":".into(), "\"".into(), "*".into()];
        let mut s = smpl::init_dry(Some(&vocab), 0.8, 1.75, 2, 64, &brk);
        let accept_line = format!(
            "DRY9 ACCEPT{}",
            stream.iter().map(|t| format!(",{t}")).collect::<String>()
        );
        assert_eq!(accept_line, get("DRY9 ACCEPT").unwrap(), "DRY9 stream");
        for &t in &stream {
            s.accept(t);
        }
        let mut cur = TokenDataArray {
            data: cands9
                .iter()
                .map(|&(id, l)| TokenData {
                    id,
                    logit: l,
                    p: 0.0,
                })
                .collect(),
            size: cands9.len(),
            selected: -1,
            sorted: false,
        };
        s.apply(&mut cur);
        let mut out = String::from("DRY9 APPLY");
        for d in cur.data[..cur.size].iter() {
            out.push_str(&format!(" {}={:08x}", d.id, d.logit.to_bits()));
        }
        assert_eq!(out, get("DRY9 APPLY").unwrap(), "DRY9 apply");
    }

    // ------------------------------------------------------------------
    // full chain: penalties -> dry -> top_k -> top_p -> min_p -> temp -> dist
    // ------------------------------------------------------------------
    let chain_case = |label: &str, temp: f32, n_steps: usize| {
        let mut p = SamplingParams {
            temp,
            seed: 42,
            penalty_last_n: 16,
            penalty_repeat: 1.1,
            penalty_freq: 0.30,
            penalty_present: 0.25,
            dry_multiplier: 0.8,
            dry_base: 1.75,
            dry_allowed_length: 2,
            dry_penalty_last_n: 64,
            top_k: 40,
            top_p: 0.95,
            min_p: 0.05,
            samplers: vec![
                CommonSamplerType::Penalties,
                CommonSamplerType::Dry,
                CommonSamplerType::TopK,
                CommonSamplerType::TopP,
                CommonSamplerType::MinP,
                CommonSamplerType::Temperature,
            ],
            ..Default::default()
        };
        p.dry_sequence_breakers = vec!["\n".into(), ":".into(), "\"".into(), "*".into()];

        let mut ctx = SamplingContext::new_with_vocab(n_vocab as i32, Some(&vocab), p);
        for &t in &rep[..12] {
            ctx.accept(t);
        }

        let mut logits = vec![-3.0f32; n_vocab];
        for &t in &rep {
            logits[t as usize] = 2.0;
        }
        logits[5] = 1.9;
        logits[6] = 1.8;
        logits[7] = 1.7;

        for step in 0..n_steps {
            let tok = ctx.sample(&logits);
            assert_eq!(
                format!("DRYCHAIN {label} STEP {step} tok {tok}"),
                get(&format!("DRYCHAIN {label} STEP {step}")).unwrap(),
                "{label} step {step}"
            );
        }
    };

    chain_case("GREEDY", 0.0, 8);
    chain_case("TEMP", 0.8, 12);

    // ------------------------------------------------------------------
    // adaptive-p
    // ------------------------------------------------------------------
    {
        let mut logits = vec![-3.0f32; n_vocab];
        for &t in &rep {
            logits[t as usize] = 2.0;
        }
        logits[5] = 1.9;
        logits[6] = 1.8;
        logits[7] = 1.7;

        for (label, target) in [("ADAPTIVE1", 0.30f32), ("ADAPTIVE2", 0.05f32)] {
            let mut s = smpl::init_adaptive_p(target, 0.9, 42);
            for step in 0..10 {
                let mut cur = TokenDataArray::from_logits(&logits);
                s.apply(&mut cur);
                let tok = cur.selected_token().unwrap();
                s.accept(tok);
                assert_eq!(
                    format!("{label} STEP {step} sel {tok}"),
                    get(&format!("{label} STEP {step}")).unwrap(),
                    "{label} step {step}"
                );
            }
        }

        // negative target = disabled: plain dist sampling
        {
            let mut s = smpl::init_adaptive_p(-1.0, 0.9, 42);
            for step in 0..4 {
                let mut cur = TokenDataArray::from_logits(&logits);
                s.apply(&mut cur);
                let tok = cur.selected_token().unwrap();
                s.accept(tok);
                assert_eq!(
                    format!("ADAPTIVE3 STEP {step} sel {tok}"),
                    get(&format!("ADAPTIVE3 STEP {step}")).unwrap()
                );
            }
        }
    }

    // ------------------------------------------------------------------
    // infill (real vocab pieces + EOG attrs)
    // ------------------------------------------------------------------
    {
        let pick: Vec<i32> = {
            let mut v: Vec<i32> = Vec::new();
            for s in ["h", "he", "hel", "hell", "hello", " world", "\n", ":"] {
                let t = vocab.tokenize_bytes(s.as_bytes(), false, false);
                if !t.is_empty() {
                    v.push(*t.last().unwrap());
                }
            }
            v
        };
        let ids_line = format!(
            "INFILL1 IDS{}",
            pick.iter().map(|t| format!(",{t}")).collect::<String>()
        );
        assert_eq!(
            ids_line,
            get("INFILL1 IDS").unwrap(),
            "infill candidate ids"
        );

        let probs1 = [0.30f32, 0.15, 0.12, 0.10, 0.08, 0.13, 0.06, 0.06];
        let probs2 = [0.001f32, 0.001, 0.001, 0.001, 0.001, 0.001, 0.6, 0.394];

        for (label, probs) in [("INFILL1", &probs1[..]), ("INFILL2", &probs2[..])] {
            let mut s = smpl::init_infill(&vocab);
            let mut cur = TokenDataArray {
                data: pick
                    .iter()
                    .zip(probs)
                    .map(|(&id, &p)| TokenData {
                        id,
                        logit: (p as f64).ln() as f32,
                        p: 0.0,
                    })
                    .collect(),
                size: pick.len(),
                selected: -1,
                sorted: false,
            };
            s.apply(&mut cur);
            let mut out = format!("{label} APPLY");
            for d in cur.data[..cur.size].iter() {
                out.push_str(&format!(" {}={:08x}", d.id, d.p.to_bits()));
            }
            assert_eq!(
                out,
                get(&format!("{label} APPLY")).unwrap(),
                "{label} apply"
            );
        }
    }
}

/// `common_sampler_types_from_names` / `_from_chars` mapping parity
/// (common/sampling.cpp:795-919) — pure-string, no vocab needed.
#[test]
fn sampler_type_name_and_char_mapping() {
    use CommonSamplerType::*;

    // canonical + kebab + nodash + misc aliases
    let names: Vec<String> = vec![
        "dry",
        "top_k",
        "top-k",
        "topk",
        "typ_p",
        "typ-p",
        "typp",
        "typ",
        "top_p",
        "top-p",
        "nucleus",
        "top_n_sigma",
        "top-n-sigma",
        "topnsigma",
        "min_p",
        "min-p",
        "temperature",
        "temp",
        "xtc",
        "infill",
        "penalties",
        "adaptive_p",
        "adaptive-p",
        "adaptivep",
    ]
    .into_iter()
    .map(String::from)
    .collect();
    let got = smpl::common_sampler_types_from_names(&names);
    assert_eq!(
        got,
        vec![
            Dry,
            TopK,
            TopK,
            TopK,
            TypicalP,
            TypicalP,
            TypicalP,
            TypicalP,
            TopP,
            TopP,
            TopP,
            TopNSigma,
            TopNSigma,
            TopNSigma,
            MinP,
            MinP,
            Temperature,
            Temperature,
            Xtc,
            Infill,
            Penalties,
            AdaptiveP,
            AdaptiveP,
            AdaptiveP,
        ]
    );

    // case-insensitive, unknown names skipped
    let got = smpl::common_sampler_types_from_names(&["TOP-K".to_string(), "bogus".to_string()]);
    assert_eq!(got, vec![TopK]);

    // chars: dkypsmtxiea
    let got = smpl::common_sampler_types_from_chars("dkypsm txiea");
    assert_eq!(
        got,
        vec![
            Dry,
            TopK,
            TypicalP,
            TopP,
            TopNSigma,
            MinP,
            Temperature,
            Xtc,
            Infill,
            Penalties,
            AdaptiveP,
        ]
    );
    assert!(smpl::common_sampler_types_from_chars("zZ?").is_empty());

    // to_str / to_chr round trip (the server's /props echo uses to_str)
    for t in [
        Dry,
        TopK,
        TypicalP,
        TopP,
        TopNSigma,
        MinP,
        Temperature,
        Xtc,
        Infill,
        Penalties,
        AdaptiveP,
    ] {
        assert_eq!(
            smpl::common_sampler_types_from_chars(&t.to_chr().to_string()),
            vec![t]
        );
        assert_eq!(
            smpl::common_sampler_types_from_names(&[t.to_str().to_string()]),
            vec![t]
        );
    }
}

/// DRY init-dry_testing (token-based breakers, the test-sampling.cpp wrapper)
/// and the disabled-sampler branches.
#[test]
fn dry_testing_and_disabled_paths() {
    use llama::sampling::init_dry;

    // disabled: multiplier 0 / base < 1 / last_n 0 -> "?dry" no-op
    assert_eq!(init_dry(None, 0.0, 1.75, 2, 64, &[]).name(), "?dry");
    assert_eq!(init_dry(None, 0.8, 0.9, 2, 64, &[]).name(), "?dry");
    assert_eq!(init_dry(None, 0.8, 1.75, 2, 0, &[]).name(), "?dry");
    assert_eq!(init_dry(None, 0.8, 1.75, 2, -3, &[]).name(), "?dry"); // clamped to 0

    // token-based breakers via init_dry_testing: stream [1,2,3,1,2,3] with a
    // single-token breaker on 9 — the token after a repeat of [1,2,3] is 1,
    // so 1 gets penalized; 9 exempt as a single-token breaker head
    let mut s = smpl::init_dry_testing(0.8, 1.75, 2, 16, &[&[9], &[7, 8]]);
    for t in [1, 2, 3, 1, 2, 3] {
        s.accept(t);
    }
    let mut cur = TokenDataArray::from_logits(&[0.5, 0.4, 0.3, 0.2, 0.1]);
    // remap ids: candidates 0..4 map to tokens 1..3 + two fillers
    cur.data[0].id = 1;
    cur.data[1].id = 2;
    cur.data[2].id = 3;
    cur.data[3].id = 4;
    cur.data[4].id = 9;
    s.apply(&mut cur);
    // token 1 extends the length-3 repeat [1,2,3] -> repeat 3 > allowed 2:
    // penalty = 0.8 * 1.75^1 = 1.4
    assert!(
        (cur.data[0].logit - (0.5f32 - 1.4)) < 1e-6,
        "{}",
        cur.data[0].logit
    );
    // tokens 2/3 do not end longer repeats than [3]/[2,3] -> unchanged
    assert_eq!(cur.data[1].logit, 0.4);
    assert_eq!(cur.data[2].logit, 0.3);
    assert_eq!(cur.data[3].logit, 0.2);

    // reset clears the ring
    s.reset();
    let mut cur2 = TokenDataArray::from_logits(&[0.5, 0.4]);
    cur2.data[0].id = 1;
    cur2.data[1].id = 2;
    s.apply(&mut cur2);
    assert_eq!(cur2.data[0].logit, 0.5); // no history -> no penalty
}
