//! t5_e2e.rs — T5-encoder (`LlmArch::T5ENCODER`, models/t5.cpp graph<true> +
//! models/t5encoder.cpp) loader + encoder verification on the real local GGUF.
//!
//! Model: `/home/jeffrey/localai/models/t5-v1_1-xxl-encoder-Q5_K_S.gguf`
//! (24 encoder layers, d_model 4096, 64 heads x 64, d_ff 10240, Q5_K).
//!
//! Ground truth: `parity/encode_t5enc_*.bin`, produced by
//! `parity/ref_encode_dump.cpp` against the pinned reference libllama.so
//! (`llama_encode` + `llama_get_embeddings`) — regenerate with
//! `bash parity/gen_encode_ref.sh`. Token ids travel inside the artifact.
//!
//! Runs by default (cheap — GGUF header + mmap, no forward):
//!   * `t5encoder_xxl_loader_tensor_map` — exact tensor counts/shapes/types and
//!     the t5 hparams the encoder reads (`n_rel_attn_bkts` included).
//!   * `t5encoder_xxl_encode_graph_shape` — the built (not computed) encoder
//!     graph: output shapes, node counts, the relative-position bias added to
//!     every layer's pre-softmax logits, kq_scale == 1.0.
//!   * `relative_position_bucket_matches_reference` — the whole bucket table vs
//!     `parity/t5_bucket_ref.txt` (generated by `parity/ref_t5_bucket.c`, a
//!     verbatim copy of llama-graph.cpp:3890-3923), bidirectional and
//!     unidirectional.
//!   * `t5encoder_reference_dump_shape` — the artifacts the heavy test assumes.
//!
//! `#[ignore]`d (heavy; 24 x 4096-dim Q5_K layers):
//!   * `t5encoder_xxl_encode_vs_reference` — the full forward for NONE and MEAN
//!     pooling vs the reference dumps + determinism.
//!     Run: `cargo test -p llama --release --test t5_e2e -- --ignored --nocapture`
//!
//! Tail: identical story to BERT (see `bert_e2e.rs`'s header and PARITY.md).
//! Q5_K GEMMs go through `ggml_vec_dot_q5_K_q8_K` on both sides (llamafile
//! `sgemm` rejects the Q8_K activation type), so the only seeds are the F32
//! attention GEMMs (tinyBLAS at m % 4 == 0 && k % 16 == 0, or this port's f32
//! vec_dot tail for k % 64 != 0). At T=1 both sides take the same kernels and
//! the port is bit-exact to 1-2 ulp; for T >= 2 the Q8_K/Q8_0 activation
//! quantization amplifies those seeds (documented mechanism).

use std::path::Path;
use std::sync::Arc;

use ggml::tensor::GgmlOp;
use ggml::Gguf;
use llama::context::{EncoderContext, EncoderWeights};
use llama::graph_arch::{relative_position_bucket, EncoderParams, T5EncoderModelWeights};
use llama::hparams::LlamaPoolingType as P;
use llama::model::{load_model, LlamaModel};
use memmap2::Mmap;

const T5ENC: &str = "/home/jeffrey/localai/models/t5-v1_1-xxl-encoder-Q5_K_S.gguf";
const REF_BUCKETS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/t5_bucket_ref.txt"
);
const REF_PER_TOKEN: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/encode_t5enc_pertoken.bin"
);
const REF_MEAN: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/encode_t5enc_mean.bin"
);
const REF_SINGLE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../parity/encode_t5enc_single.bin"
);

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn open_model(path: &str) -> Option<(Gguf, Arc<Mmap>)> {
    if !Path::new(path).exists() {
        eprintln!("skipping: {path} not present");
        return None;
    }
    let file = std::fs::File::open(path).unwrap();
    // SAFETY: model files are read-only for us (same policy as Gguf::open)
    let mmap = Arc::new(unsafe { Mmap::map(&file).unwrap() });
    let gguf = Gguf::from_bytes(mmap.clone()).expect("gguf parse");
    Some((gguf, mmap))
}

fn load_t5(path: &str) -> Option<LlamaModel> {
    let (gguf, mmap) = open_model(path)?;
    Some(load_model(&gguf, mmap).expect("load_model"))
}

struct RefDump {
    n_tokens: usize,
    n_embd_out: usize,
    n_rows: usize,
    pooling: i32,
    tokens: Vec<i32>,
    values: Vec<f32>,
}

fn read_ref(path: &str) -> Option<RefDump> {
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("SKIP: cannot read {path}: {e} (run parity/gen_encode_ref.sh)");
            return None;
        }
    };
    assert_eq!(&bytes[..8], b"LENCE1\0\0", "{path}: magic");
    let u32at = |o: usize| u32::from_le_bytes(bytes[o..o + 4].try_into().unwrap()) as usize;
    let (n_tokens, n_embd_out, n_rows, pooling) =
        (u32at(8), u32at(12), u32at(16), u32at(20) as i32);
    let mut off = 24;
    let tokens: Vec<i32> = bytes[off..off + 4 * n_tokens]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes(c.try_into().unwrap()))
        .collect();
    off += 4 * n_tokens;
    let values: Vec<f32> = bytes[off..off + 4 * n_embd_out * n_rows]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect();
    assert_eq!(values.len(), n_embd_out * n_rows, "{path}: payload size");
    Some(RefDump {
        n_tokens,
        n_embd_out,
        n_rows,
        pooling,
        tokens,
        values,
    })
}

/// `EncoderParams` from the loaded hparams (t5 reads `f_norm_rms_eps` for
/// LLM_NORM_RMS and `n_rel_attn_bkts` for build_pos_bias).
fn t5_params(m: &LlamaModel, pool: P) -> EncoderParams {
    let hp = &m.hparams;
    EncoderParams {
        n_head: hp.n_head(0) as i64,
        n_head_kv: hp.n_head_kv(0) as i64,
        n_embd_head: hp.n_embd_head_k(0) as i64,
        n_rel_attn_bkts: hp.n_rel_attn_bkts,
        f_norm_eps: hp.f_norm_eps,
        f_norm_rms_eps: hp.f_norm_rms_eps,
        pool: llama::context::resolve_pooling(pool, hp.pooling_type),
        euro_rope: None,
        gemma_swa: None,
        causal: false,
    }
}

fn encoder(m: LlamaModel, pool: P) -> EncoderContext {
    let params = t5_params(&m, pool);
    let weights = EncoderWeights::T5Encoder(m.t5_encoder_weights());
    EncoderContext::new(m.ctx, weights, params, 8)
}

struct Stats {
    bits: usize,
    mean_abs: f32,
    max_abs: f32,
    rms: f32,
    rel_mean: f32,
    rel: f32,
    rel_eps: f32,
}

fn report(tag: &str, got: &[f32], want: &[f32]) -> Stats {
    assert_eq!(got.len(), want.len(), "length mismatch");
    let mut bits = 0usize;
    let mut sum_abs = 0f64;
    let mut max_abs = 0f32;
    let mut sq = 0f64;
    let mut rel_eps = 0f32;
    for (a, b) in got.iter().zip(want) {
        if a.to_bits() == b.to_bits() {
            bits += 1;
        }
        let d = (a - b).abs();
        sum_abs += d as f64;
        max_abs = max_abs.max(d);
        sq += (*b as f64) * (*b as f64);
        if b.abs() > 1e-3 {
            rel_eps = rel_eps.max(d / b.abs());
        }
    }
    let n = got.len() as f64;
    let rms = (sq / n).sqrt() as f32;
    let mean_abs = (sum_abs / n) as f32;
    let s = Stats {
        bits,
        mean_abs,
        max_abs,
        rms,
        rel_mean: mean_abs / rms,
        rel: max_abs / rms,
        rel_eps,
    };
    println!(
        "{tag}: n={} bit-exact={} ({:.2}%) mean_d={:.3e} max_d={:.3e} ref_rms={:.4} \
         mean_d/rms={:.3e} max_d/rms={:.3e} rel_gt_1e-3={:.3e}",
        got.len(),
        s.bits,
        100.0 * s.bits as f64 / got.len() as f64,
        s.mean_abs,
        s.max_abs,
        s.rms,
        s.rel_mean,
        s.rel,
        s.rel_eps,
    );
    s
}

// ---------------------------------------------------------------------------
// default-run tests
// ---------------------------------------------------------------------------

/// Full tensor map of the real t5-v1_1-xxl-encoder file: 219 gguf tensors
/// (24 layers x 9 + `enc.blk.0.attn_rel_b` + token_embd + enc.output_norm), all
/// consumed, plus the hparams the encoder graph reads.
#[test]
fn t5encoder_xxl_loader_tensor_map() {
    let Some((gguf, mmap)) = open_model(T5ENC) else {
        return;
    };
    let m = load_model(&gguf, mmap).expect("t5-v1_1-xxl-encoder must load");

    assert_eq!(m.arch, llama::arch::LlmArch::T5ENCODER);
    assert_eq!(gguf.tensors.len(), 219, "file tensor count");
    assert_eq!(m.tensors.len(), 219, "loaded tensor count");
    // no decoder tensors in an encoder-only file, and none created
    assert!(
        m.tensors.keys().all(|k| !k.starts_with("dec.")),
        "decoder tensor loaded"
    );

    let hp = &m.hparams;
    assert_eq!(hp.n_layer(), 24);
    assert_eq!(hp.n_embd, 4096);
    assert_eq!(hp.n_ff(0), 10240);
    assert_eq!(hp.n_head(0), 64);
    assert_eq!(hp.n_head_kv(0), 64);
    assert_eq!(hp.n_embd_head_k(0), 64);
    assert_eq!(hp.n_embd_head_v(0), 64);
    assert_eq!(hp.n_embd_k_gqa(0), 4096);
    assert_eq!(hp.n_embd_v_gqa(0), 4096);
    assert_eq!(hp.n_ctx_train, 512);
    // the two t5-only hparams (models/t5encoder.cpp:4-5)
    assert!(
        (hp.f_norm_rms_eps - 1e-6).abs() < 1e-12,
        "layer_norm_rms_epsilon"
    );
    assert_eq!(hp.n_rel_attn_bkts, 32, "attention.relative_buckets_count");
    // the file has no pooling key -> UNSPECIFIED -> NONE
    assert_eq!(hp.pooling_type, P::UNSPECIFIED);

    let ne = |id| *m.ctx.ne(id);
    let ty = |id| m.ctx.ty(id);
    assert_eq!(ne(m.tok_embd), [4096, 32128, 1, 1]);
    // Q5_K_S: the token embedding is the one q6_K tensor in this file
    assert_eq!(ty(m.tok_embd), ggml::types::GgmlType::Q6K);
    // t5encoder.cpp:17 — `output_norm_enc` lands on the model's output_norm slot
    assert_eq!(ne(m.output_norm), [4096, 1, 1, 1]);
    assert_eq!(ty(m.output_norm), ggml::types::GgmlType::F32);
    // no output.weight -> duplicated token_embd (t5encoder.cpp:18-22)
    assert_eq!(m.output, m.tok_embd);

    assert_eq!(m.layers.len(), 24);
    let mut rel_b_layers = 0;
    for (il, l) in m.layers.iter().enumerate() {
        assert_eq!(ne(l.enc_attn_norm.expect("enc_attn_norm")), [4096, 1, 1, 1]);
        assert_eq!(ne(l.enc_wq.expect("enc_wq")), [4096, 4096, 1, 1]);
        assert_eq!(ne(l.enc_wk.expect("enc_wk")), [4096, 4096, 1, 1]);
        assert_eq!(ne(l.enc_wv.expect("enc_wv")), [4096, 4096, 1, 1]);
        assert_eq!(ne(l.enc_wo.expect("enc_wo")), [4096, 4096, 1, 1]);
        assert_eq!(ne(l.enc_ffn_norm.expect("enc_ffn_norm")), [4096, 1, 1, 1]);
        assert_eq!(ne(l.enc_ffn_up.expect("enc_ffn_up")), [4096, 10240, 1, 1]);
        assert_eq!(
            ne(l.enc_ffn_down.expect("enc_ffn_down")),
            [10240, 4096, 1, 1]
        );
        assert_eq!(ne(l.enc_ffn_gate.expect("ffn_gate")), [4096, 10240, 1, 1]);
        if let Some(rb) = l.enc_attn_rel_b {
            // t5encoder.cpp:28 — {n_head, n_rel_attn_bkts}
            assert_eq!(ne(rb), [64, 32, 1, 1], "layer {il} attn_rel_b");
            assert_eq!(ty(rb), ggml::types::GgmlType::F32);
            rel_b_layers += 1;
        }
        // t5 v1.1 is gated (gelu), not the t5 1.0 relu FFN
        assert!(l.enc_ffn_gate.is_some(), "layer {il}: v1.1 has ffn_gate");
        // decoder-side members must stay unloaded
        assert!(l.attn_norm.is_none() && l.wq.is_none() && l.ffn_gate.is_none());
    }
    // only blk.0 ships the relative bias table; the graph falls back to it
    // (t5.cpp:305)
    assert_eq!(rel_b_layers, 1, "only enc.blk.0.attn_rel_b exists");

    let w: T5EncoderModelWeights = m.t5_encoder_weights();
    assert_eq!(w.layers.len(), 24);
    assert_eq!(w.output_norm_enc, m.output_norm);
    assert!(w.layers[1..].iter().all(|l| l.attn_rel_b_enc.is_none()));
    assert!(w.layers[0].attn_rel_b_enc.is_some());
}

/// `llama_relative_position_bucket` (llama-graph.cpp:3890-3923) against the
/// verbatim C table in parity/t5_bucket_ref.txt: every (x, y) pair of the 12
/// probe positions (bidirectional, n_buckets = 32) and the 0..16 unidirectional
/// grid. This is what pins the float/double typing of the log formula.
#[test]
fn relative_position_bucket_matches_reference() {
    let Ok(txt) = std::fs::read_to_string(REF_BUCKETS) else {
        eprintln!("SKIP: {REF_BUCKETS} missing (run parity/ref_t5_bucket)");
        return;
    };
    let mut checked = 0usize;
    let mut bi = 0usize;
    let mut uni = 0usize;
    for line in txt.lines() {
        let f: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(f.len(), 4, "bad line {line:?}");
        let x: i32 = f[1].parse().unwrap();
        let y: i32 = f[2].parse().unwrap();
        let want: i32 = f[3].parse().unwrap();
        let got = match f[0] {
            "bi" => {
                bi += 1;
                relative_position_bucket(x, y, 32, true)
            }
            "uni" => {
                uni += 1;
                relative_position_bucket(x, y, 32, false)
            }
            other => panic!("bad mode {other}"),
        };
        assert_eq!(got, want, "{f:?}: bucket mismatch");
        checked += 1;
    }
    println!("relative_position_bucket: {checked} reference entries match ({bi} bi, {uni} uni)");
    assert_eq!(checked, 433);
    // spot checks (values read from the C table above): 32 buckets halve to 16
    // per direction, 8 exact slots then log spacing; every positive delta also
    // carries the +16 "past" direction offset (llama-graph.cpp:3903-3904)
    assert_eq!(relative_position_bucket(0, 0, 32, true), 0);
    assert_eq!(relative_position_bucket(7, 0, 32, true), 23); // 7 + 16
    assert_eq!(relative_position_bucket(8, 0, 32, true), 24); // first log slot
    assert_eq!(relative_position_bucket(15, 0, 32, true), 25);
    assert_eq!(relative_position_bucket(16, 0, 32, true), 26);
    assert_eq!(relative_position_bucket(0, 16, 32, true), 10); // mirror side
    assert_eq!(relative_position_bucket(7, 15, 32, true), 8); // clamped at max_exact
                                                              // unidirectional (decoder path, llama-kv-cache.cpp:1809) stays causal
    assert_eq!(relative_position_bucket(0, 0, 32, false), 0);
    assert_eq!(
        relative_position_bucket(16, 0, 32, false),
        0,
        "future, clamped"
    );
}

/// The built graph (no compute) — t5.cpp:281-346 + build_pos_bias.
#[test]
fn t5encoder_xxl_encode_graph_shape() {
    let Some(m) = load_t5(T5ENC) else { return };
    let Some(ref_dump) = read_ref(REF_PER_TOKEN) else {
        return;
    };
    let tokens = &ref_dump.tokens;

    let mut ctx = encoder(m, P::NONE);
    let g = ctx.build(tokens).expect("build");
    assert_eq!(*ctx.gctx.ne(g.embd), [4096, tokens.len() as i64, 1, 1]);
    assert_eq!(g.layer_outs.len(), 24);

    let count = |op: GgmlOp| {
        g.graph
            .nodes
            .iter()
            .filter(|&&n| ctx.gctx.op(n) == op)
            .count()
    };
    let n = 24usize;
    assert_eq!(
        count(GgmlOp::SoftMax),
        n,
        "one softmax per layer (t5.cpp:308-310)"
    );
    assert_eq!(count(GgmlOp::Transpose), n, "cont(transpose(v)) per layer");
    // cont of transpose(v), of kqv, and of the permuted pos_bias
    assert_eq!(
        count(GgmlOp::Dup),
        3 * n,
        "cont of transpose(v), kqv and pos_bias"
    );
    // relative position bias: reshape → get_rows → reshape → permute → cont
    assert_eq!(
        count(GgmlOp::Permute),
        5 * n,
        "q/k/v + kqv + the pos_bias permute"
    );
    // one pos_bias gather per layer (llama-graph.cpp:2591) + tok_embd + the
    // last-layer out_ids pair
    assert_eq!(
        count(GgmlOp::GetRows),
        n + 3,
        "pos_bias rows per layer + embd + out_ids"
    );
    // q,k,v,kq,kqv,wo,gate,up,down = 9 matmuls per layer
    assert_eq!(count(GgmlOp::MulMat), 9 * n);
    assert_eq!(
        count(GgmlOp::Norm),
        2 * n + 1,
        "attn_norm + ffn_norm per layer + enc_norm"
    );
    assert_eq!(count(GgmlOp::Mul), 2 * n + 1, "their weights (build_norm)");
    // pos_bias is ADDED to kq before the softmax (llama-graph.cpp:2706-2710):
    // two residuals + kq_b per layer, and T5 has no biases at all
    assert_eq!(
        count(GgmlOp::Add),
        3 * n,
        "attn residual + ffn residual + kq_b per layer"
    );
    // GELU is GgmlOp::Silu with param 8 => the gated `ggml_geglu_split` path
    let glu = g
        .graph
        .nodes
        .iter()
        .filter(|&&x| ctx.gctx.op(x) == GgmlOp::Glu)
        .count();
    assert_eq!(glu, n, "one geglu per layer (t5.cpp:328-335)");
    // per layer: norm 2, mul 2, add 3, softmax 1, transpose 1, cont 3, permute 5,
    // matmul 9, glu 1, get_rows 1, reshape 6  ==  34; plus enc_norm (norm+mul)
    // and the 3 model-level get_rows  ==  821
    println!("t5 encoder graph: {} nodes", g.graph.nodes.len());
    assert_eq!(
        g.graph.nodes.len(),
        821,
        "total nodes of the t5-xxl encoder graph"
    );

    // MEAN pooling adds the build_inp_mean matmul on top
    let Some(m) = load_t5(T5ENC) else { return };
    let mut ctx = encoder(m, P::MEAN);
    let g = ctx.build(tokens).expect("build");
    assert_eq!(*ctx.gctx.ne(g.pooled), [4096, 1, 1, 1]);
    assert_eq!(ctx.gctx.op(g.pooled), GgmlOp::MulMat);
}

#[test]
fn t5encoder_reference_dump_shape() {
    let Some(d) = read_ref(REF_PER_TOKEN) else {
        return;
    };
    assert_eq!(d.n_embd_out, 4096);
    assert_eq!(d.n_rows, d.n_tokens);
    assert_eq!(d.pooling, 0, "the file has no pooling_type key -> NONE");
    // the t5 vocabulary: id 1 = </s> is appended by the tokenizer
    assert_eq!(d.tokens[0], 13959);
    assert_eq!(*d.tokens.last().unwrap(), 1, "add_eos_token = true");

    let Some(s) = read_ref(REF_SINGLE) else {
        return;
    };
    assert_eq!(s.tokens, vec![0], "--ids 0 pins the pad token");
    assert_eq!((s.n_embd_out, s.n_rows), (4096, 1));

    let Some(mn) = read_ref(REF_MEAN) else { return };
    assert_eq!(mn.tokens, d.tokens);
    assert_eq!(mn.pooling, 1, "explicit MEAN");
    assert_eq!((mn.n_embd_out, mn.n_rows), (4096, 1));
    for j in (0..4096).step_by(97) {
        let want: f32 = d.values.iter().skip(j).step_by(4096).sum::<f32>() / d.n_tokens as f32;
        assert!(
            (want - mn.values[j]).abs() < 2e-3,
            "mean[{j}]: reference mean {} vs recomputed {want}",
            mn.values[j]
        );
    }
}

// ---------------------------------------------------------------------------
// heavy test (real forward)
// ---------------------------------------------------------------------------

const T_MULTI_TOL: f32 = 3e-2;

#[test]
#[ignore]
fn t5encoder_xxl_encode_vs_reference() {
    let Some(ref_single) = read_ref(REF_SINGLE) else {
        return;
    };
    let Some(ref_none) = read_ref(REF_PER_TOKEN) else {
        return;
    };

    // ---- T=1 anchor ----
    let Some(m) = load_t5(T5ENC) else { return };
    let mut c1 = encoder(m, P::NONE);
    let g1 = c1.encode(&ref_single.tokens).expect("encode");
    let s1 = report("t5 T=1 ", &g1.values, &ref_single.values);
    assert!(
        s1.rel < 1e-6,
        "T=1 anchor drifted: max|d|/rms={:.3e}",
        s1.rel
    );

    // ---- T=17 ----
    let tokens = ref_none.tokens.clone();
    let Some(m) = load_t5(T5ENC) else { return };
    let mut c = encoder(m, P::NONE);
    let got = c.encode(&tokens).expect("encode");
    assert_eq!(
        (got.n_embd_out, got.n_rows),
        (ref_none.n_embd_out, ref_none.n_tokens)
    );
    let s = report("t5 T=17", &got.values, &ref_none.values);
    assert!(
        s.rel_mean < T_MULTI_TOL,
        "t5 NONE mean|d|/rms {:.3e} above the documented tail",
        s.rel_mean
    );

    // determinism
    let Some(m) = load_t5(T5ENC) else { return };
    let mut c2 = encoder(m, P::NONE);
    let got2 = c2.encode(&tokens).expect("encode");
    let bits = got
        .values
        .iter()
        .zip(&got2.values)
        .filter(|(a, b)| a.to_bits() == b.to_bits())
        .count();
    println!("t5 determinism: {bits}/{} bit-identical", got.values.len());
    assert_eq!(bits, got.values.len(), "encode is not deterministic");
    let got3 = c.encode(&tokens).expect("encode (reuse)");
    let bits3 = got
        .values
        .iter()
        .zip(&got3.values)
        .filter(|(a, b)| a.to_bits() == b.to_bits())
        .count();
    println!("t5 reuse      : {bits3}/{} bit-identical", got.values.len());
    assert_eq!(bits3, got.values.len(), "encode reuse is not deterministic");

    // ---- MEAN pooling ----
    if let Some(ref_mean) = read_ref(REF_MEAN) {
        let Some(m) = load_t5(T5ENC) else { return };
        let mut c = encoder(m, P::MEAN);
        let got = c.encode(&tokens).expect("encode");
        assert_eq!(got.n_rows, 1);
        let ref_mean_of_rows: Vec<f32> = (0..4096)
            .map(|j| {
                ref_none.values.iter().skip(j).step_by(4096).sum::<f32>() / ref_none.n_tokens as f32
            })
            .collect();
        let sm = report("t5 MEAN", &got.values, &ref_mean.values);
        let sr = report("t5 MEAN*", &got.values, &ref_mean_of_rows);
        assert!(sm.rel_mean.min(sr.rel_mean) < T_MULTI_TOL);
    }

    // ---- keep_layer_outs: the last layer output feeds enc_norm (t5.cpp:350) ----
    let Some(m) = load_t5(T5ENC) else { return };
    let mut c = encoder(m, P::NONE);
    c.keep_layer_outs = true;
    let out = c.encode(&tokens).expect("encode");
    assert_eq!(out.layer_outs.len(), 24);
    assert_eq!(out.layer_outs[23].len(), 4096 * tokens.len());
    // enc_norm is applied *after* the last layer (t5.cpp:350-355). T5's
    // pre-norm residual stream is very large by design (the relative norms
    // rescale it away), so the two rms values are only informative here: the
    // output rms tracks `enc.output_norm.weight`'s rms because RMSNorm divides
    // the scale out.
    let rms_last = (out.layer_outs[23].iter().map(|v| v * v).sum::<f32>()
        / out.layer_outs[23].len() as f32)
        .sqrt();
    let rms_out = (out.values.iter().map(|v| v * v).sum::<f32>() / out.values.len() as f32).sqrt();
    println!("t5 layer-23 rms {rms_last:.4} -> enc_norm output rms {rms_out:.4}");
    // the reference's own sidecar for this run reports rms=0.1044 on the
    // enc_norm output; assert we land on the same scale
    assert!(
        (0.05..0.2).contains(&rms_out),
        "enc_norm output rms {rms_out} unexpected"
    );
    // the norm's output must be independent of the input scale: re-running the
    // same encode with a scaled layer-23 output is not expressible here, but
    // the bit-exact T=1 comparison above already pins the whole chain.
    assert!(
        rms_last > 10.0 * rms_out,
        "layer 23 should carry the un-normalized stream"
    );
}
