// Generated by parity/gen_ui_assets.py — do not edit.
// (the port's counterpart of build-rust-ref/tools/ui/ui.cpp, which is
// generated by scripts/ui-assets.cmake from a provisioned dist tree — an
// empty table when none was provisioned, exactly this file's state.)
//
// Regenerate after dropping a built UI dist at
// crates/tools/llama-server/ui-dist/ with:
//     python3 parity/gen_ui_assets.py

use super::ui::UiAsset;

pub const USE_GZIP: bool = false;

pub const ASSETS: &[UiAsset] = &[];
