#!/usr/bin/env python3
"""arch_gen.py — generate crates/llama/src/arch.rs from the pinned llama.cpp source.

Extracts, in declaration order:
  - `enum llm_arch`   + LLM_ARCH_NAMES   (llama-arch.h / llama-arch.cpp)
  - `enum llm_kv`     + LLM_KV_NAMES
  - `enum llm_tensor` + LLM_TENSOR_NAMES + LLM_TENSOR_INFOS (layer classification only)

and emits the complete arch.rs (tables are generated; the hand-written logic at
the bottom mirrors llama-arch.cpp's free functions).

std::map semantics: initializer-list construction keeps the FIRST entry for a
duplicated key — the generator does the same and reports the duplicates.

Usage: python3 arch_gen.py [--check]   (--check: verify arch.rs is up to date)
"""

import os
import re
import sys
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
# sync 2026-10-08: the port now tracks the NEW baseline worktree @ c35b66744
# (the old pinned tree bd4f514db1 stays read-only for old-behavior questions)
REF = Path(os.environ.get("LLAMA_ARCH_GEN_REF", "/home/jeffrey/llm/llama.cpp-next"))
OUT = HERE / "arch.rs"


def die(msg):
    print(f"arch_gen.py: {msg}", file=sys.stderr)
    sys.exit(1)


def read(path):
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------- parsing ---

def parse_enum(h_text, enum_name):
    """Return the list of C enumerator names of `enum <enum_name> { ... };`."""
    m = re.search(rf"enum {enum_name}\s*\{{(.*?)\}};", h_text, re.S)
    if not m:
        die(f"enum {enum_name} not found")
    body = m.group(1)
    body = re.sub(r"//.*", "", body)
    names = [n.strip() for n in body.split(",") if n.strip()]
    return names


def find_map_block(cpp_text, map_name):
    """Return the inner body of `... <map_name> = { ... };`."""
    m = re.search(rf"\b{map_name}\s*=\s*\{{", cpp_text)
    if not m:
        die(f"map {map_name} not found")
    start = m.end()  # just past '{'
    depth = 1
    i = start
    while i < len(cpp_text):
        c = cpp_text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return cpp_text[start:i]
        i += 1
    die(f"map {map_name} not terminated")


def parse_kv_map(block):
    """Entries like `{ LLM_ARCH_LLAMA, "llama" },` -> [(key, value)]. First wins."""
    out = []
    for m in re.finditer(r"\{\s*(LLM_[A-Z_0-9]+)\s*,\s*\"((?:[^\"\\]|\\.)*)\"\s*\}", block):
        out.append((m.group(1), m.group(2)))
    return out


def parse_info_map(block):
    """Entries like `{LLM_TENSOR_X, {LLM_TENSOR_LAYER_INPUT, GGML_OP_GET_ROWS}},`."""
    out = []
    for m in re.finditer(
        r"\{\s*(LLM_TENSOR_[A-Z_0-9]+)\s*,\s*\{\s*(LLM_TENSOR_LAYER_[A-Z]+)\s*,\s*GGML_OP_[A-Z0-9_]+\s*\}\s*\}",
        block,
    ):
        out.append((m.group(1), m.group(2)))
    return out


# ------------------------------------------------------------- generation ---

def rust_variant(c_name, prefix):
    """LLM_ARCH_QWEN2 + LLM_ARCH_ -> QWEN2 (verbatim, greppable against the C name)."""
    assert c_name.startswith(prefix), c_name
    return c_name[len(prefix):]


HEADER = """//! arch.rs — 1:1 port of llama.cpp `src/llama-arch.cpp/.h` (c35b66744).
//!
//! Tables below are GENERATED by `arch_gen.py` (extracted from the current
//! reference source); regenerate with `python3 crates/llama/src/arch_gen.py`.
//! Hand-written logic at the bottom mirrors llama-arch.cpp free functions.
//!
//! Enum variant names intentionally keep the C SCREAMING_SNAKE names minus the
//! `LLM_ARCH_`/`LLM_KV_`/`LLM_TENSOR_` prefix so every variant greps back to
//! its C enumerator.

// llama-hparams.h
pub const LLAMA_MAX_LAYERS: usize = 512;

/// `enum llm_arch` (llama-arch.h). Order == C declaration order (matters:
/// `llm_arch_from_string` matches the first name, and std::map iteration order
/// is by enum value).
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum LlmArch {
"""


def gen_arch(names, kv_names, tensor_names, tensor_infos, arch_enum, kv_enum, tensor_enum):
    lines = []
    w = lines.append

    # --- LlmArch enum + name table ---
    w(HEADER)
    for n in arch_enum:
        v = rust_variant(n, "LLM_ARCH_")
        w(f"    {v},")
    w("}")
    w("")
    w("impl LlmArch {")
    w("    /// `llm_arch_name` — the primary GGUF name of the arch (\"(unknown)\" for UNKNOWN).")
    w("    pub fn name(self) -> &'static str {")
    w("        match self {")
    seen = set()
    for key, val in names:
        if key in seen:
            continue
        seen.add(key)
        w(f"            LlmArch::{rust_variant(key, 'LLM_ARCH_')} => \"{val}\",")
    missing = [n for n in arch_enum if n not in seen]
    if missing:
        die(f"arch enum values missing from LLM_ARCH_NAMES: {missing}")
    w("        }")
    w("    }")
    w("")
    w("    /// `llm_arch_from_string` — first matching name in enum order, None otherwise.")
    w("    pub fn from_name(s: &str) -> Option<Self> {")
    w("        Self::ALL.iter().copied().find(|&a| a.name() == s)")
    w("    }")
    w("")
    w("    /// `llm_arch_all` — every arch in enum order (includes CLIP and UNKNOWN).")
    w("    pub const ALL: &'static [LlmArch] = &[")
    for n in arch_enum:
        w(f"        LlmArch::{rust_variant(n, 'LLM_ARCH_')},")
    w("    ];")
    w("}")
    w("")

    # --- LlmKv enum + template table ---
    w("/// `enum llm_kv` (llama-arch.h). Name templates: `%s` = arch prefix, fixed")
    w("/// keys (tokenizer.*/general.*/split.*/adapter.*/xielu.*) carry no prefix.")
    w("#[allow(non_camel_case_types)]")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    w("pub enum LlmKv {")
    for n in kv_enum:
        w(f"    {rust_variant(n, 'LLM_KV_')},")
    w("}")
    w("")
    w("impl LlmKv {")
    w("    /// The raw `LLM_KV_NAMES` template (may contain a single `%s`).")
    w("    pub fn template(self) -> &'static str {")
    w("        match self {")
    seen = set()
    dups = []
    for key, val in kv_names:
        if key in seen:
            dups.append(key)
            continue
        seen.add(key)
        w(f"            LlmKv::{rust_variant(key, 'LLM_KV_')} => \"{val}\",")
    if dups:
        print(f"arch_gen.py: note: duplicate LLM_KV_NAMES keys ignored (first wins): {dups}")
    missing = [n for n in kv_enum if n not in seen]
    if missing:
        die(f"kv enum values missing from LLM_KV_NAMES: {missing}")
    w("        }")
    w("    }")
    w("}")
    w("")

    # --- LlmTensor enum + name table ---
    w("/// `enum llm_tensor` (llama-arch.h). Name templates use up to two `%d`")
    w("/// (block id, expert id), cf. `LLM_TN_IMPL::str`.")
    w("#[allow(non_camel_case_types)]")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    w("pub enum LlmTensor {")
    for n in tensor_enum:
        w(f"    {rust_variant(n, 'LLM_TENSOR_')},")
    w("}")
    w("")
    w("impl LlmTensor {")
    w("    /// The raw `LLM_TENSOR_NAMES` template; None where the C table has no")
    w("    /// entry (C++ GGML_ABORTs on use).")
    w("    pub fn template(self) -> Option<&'static str> {")
    w("        match self {")
    seen = set()
    dups = []
    for key, val in tensor_names:
        if key in seen:
            dups.append((key, val))
            continue
        seen.add(key)
        w(f"            LlmTensor::{rust_variant(key, 'LLM_TENSOR_')} => Some(\"{val}\"),")
    if dups:
        print(f"arch_gen.py: note: duplicate LLM_TENSOR_NAMES keys ignored (first wins): {dups}")
    w("            _ => None,")
    w("        }")
    w("    }")
    w("")
    w("    /// `llm_tensor_info_for(t).layer` (input/repeating/output buffer class).")
    w("    /// The ggml-op half of `llm_tensor_info` is deferred to tensor loading.")
    w("    pub fn layer(self) -> LlmTensorLayer {")
    w("        match self {")
    seen = set()
    for key, layer in tensor_infos:
        if key in seen:
            continue
        seen.add(key)
        w(f"            LlmTensor::{rust_variant(key, 'LLM_TENSOR_')} => LlmTensorLayer::{rust_variant(layer, 'LLM_TENSOR_LAYER_')},")
    w("            _ => panic!(\"no tensor info for {:?}\", self),")
    w("        }")
    w("    }")
    w("}")
    w("")
    return "\n".join(lines)


FOOTER = '''
/// `enum llm_tensor_layer` (llama-arch.h).
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LlmTensorLayer {
    INPUT,
    REPEATING,
    OUTPUT,
}

/// `LLM_KV::operator()(kv)` — resolve a KV key name for the given arch.
///
/// Mirrors `::format(LLM_KV_NAMES.at(kv), LLM_ARCH_NAMES.at(arch))`: templates
/// with a `%s` slot get the arch name (e.g. `qwen2.block_count`), fixed keys
/// (tokenizer/general/split/adapter/xielu) come back verbatim.
pub fn kv_name(arch: LlmArch, kv: LlmKv) -> String {
    let tmpl = kv.template();
    if tmpl.contains('%') {
        debug_assert!(tmpl.matches("%s").count() <= 1, "unexpected multi-%s template: {tmpl}");
        tmpl.replacen("%s", arch.name(), 1)
    } else {
        tmpl.to_string()
    }
}

/// `LLM_TN(arch)(tensor, bid)` — tensor name with the block id substituted
/// (`bid < 0` leaves non-`%d` templates untouched, like the C formatter).
pub fn tensor_name(tensor: LlmTensor, blk: i32) -> String {
    format_tensor(tensor, blk, -1)
}

/// `LLM_TN(arch)(tensor, bid, xid)` — also substitutes the second `%d`
/// (per-expert tensors, e.g. `blk.0.ffn_gate.3`).
pub fn tensor_name_xid(tensor: LlmTensor, blk: i32, xid: i32) -> String {
    format_tensor(tensor, blk, xid)
}

/// `LLM_TN(arch)(tensor, suffix, bid, xid)` — appends `.suffix`
/// (e.g. `blk.3.attn_norm.weight`).
pub fn tensor_name_suffix(tensor: LlmTensor, suffix: &str, blk: i32, xid: i32) -> String {
    let mut name = format_tensor(tensor, blk, xid);
    name.push('.');
    name.push_str(suffix);
    name
}

fn format_tensor(tensor: LlmTensor, blk: i32, xid: i32) -> String {
    // GGML_ABORT("unknown tensor name for tensor id %d", ...) in C++
    let tmpl = tensor.template().unwrap_or_else(|| panic!("unknown tensor name for tensor {tensor:?}"));
    let mut out = String::with_capacity(tmpl.len() + 8);
    let mut next_arg = 0;
    let mut rest = tmpl;
    while let Some(pos) = rest.find("%d") {
        out.push_str(&rest[..pos]);
        let arg = if next_arg == 0 { blk } else { xid };
        out.push_str(&arg.to_string());
        next_arg += 1;
        rest = &rest[pos + 2..];
    }
    out.push_str(rest);
    out
}

/// `llm_arch_is_recurrent`
pub fn llm_arch_is_recurrent(arch: LlmArch) -> bool {
    matches!(arch, LlmArch::MAMBA | LlmArch::MAMBA2 | LlmArch::RWKV6 | LlmArch::RWKV6QWEN2 | LlmArch::RWKV7 | LlmArch::ARWKV7)
}

/// `llm_arch_is_hybrid`
pub fn llm_arch_is_hybrid(arch: LlmArch) -> bool {
    matches!(
        arch,
        LlmArch::JAMBA
            | LlmArch::FALCON_H1
            | LlmArch::PLAMO2
            | LlmArch::GRANITE_HYBRID
            | LlmArch::LFM2
            | LlmArch::LFM2MOE
            | LlmArch::NEMOTRON_H
            | LlmArch::NEMOTRON_H_MOE
            | LlmArch::QWEN3NEXT
            | LlmArch::KIMI_LINEAR
            | LlmArch::BAILINGMOE3
            | LlmArch::KIMI_K3
            | LlmArch::GLM5_NEXT
            | LlmArch::QWEN35
            | LlmArch::QWEN35MOE
            | LlmArch::QWEN4EXP
            | LlmArch::DEEPSEEK4
            | LlmArch::MINIMAX_01
    )
}

/// `llm_arch_is_diffusion`
pub fn llm_arch_is_diffusion(arch: LlmArch) -> bool {
    matches!(arch, LlmArch::DREAM | LlmArch::LLADA | LlmArch::LLADA_MOE | LlmArch::RND1)
}

/// `llm_arch_supports_rs_rollback`
pub fn llm_arch_supports_rs_rollback(arch: LlmArch) -> bool {
    matches!(
        arch,
        LlmArch::KIMI_K3
            | LlmArch::QWEN35
            | LlmArch::QWEN35MOE
            | LlmArch::QWEN4EXP
            | LlmArch::DEEPSEEK4
            | LlmArch::GLM5_NEXT
            | LlmArch::NEMOTRON_H
            | LlmArch::NEMOTRON_H_MOE
            | LlmArch::LFM2
            | LlmArch::LFM2MOE
            | LlmArch::BAILINGMOE3
    )
}

/// `llm_arch_supports_sm_tensor`
pub fn llm_arch_supports_sm_tensor(arch: LlmArch) -> bool {
    !matches!(
        arch,
        LlmArch::GROK
            | LlmArch::MPT
            | LlmArch::PLAMO2
            | LlmArch::MINICPM3
            | LlmArch::GEMMA3N
            | LlmArch::MAMBA
            | LlmArch::MAMBA2
            | LlmArch::JAMBA
            | LlmArch::FALCON_H1
            | LlmArch::OLMO2
            | LlmArch::OLMOE
            | LlmArch::DEEPSEEK2
            | LlmArch::DEEPSEEK32
            | LlmArch::HY_V4
            | LlmArch::DOTS3NOTE
            | LlmArch::GLM_DSA
            | LlmArch::BITNET
            | LlmArch::T5
            | LlmArch::NEMOTRON_H
            | LlmArch::NEMOTRON_H_MOE
            | LlmArch::GRANITE_HYBRID
            | LlmArch::MINIMAX_01
            | LlmArch::MINIMAX_M2
            | LlmArch::MINIMAX_M3
            | LlmArch::MISTRAL4
            | LlmArch::KIMI_LINEAR
            | LlmArch::BAILINGMOE3
            | LlmArch::KIMI_K3
            | LlmArch::GLM5_NEXT
            | LlmArch::QWEN3TTS
            | LlmArch::K2_HORIZON
    )
}

/// `llm_arch_supports_mixed_batch` (c35b66744) — these models pick weights,
/// routing or input meaning per ubatch based on token vs embd input.
pub fn llm_arch_supports_mixed_batch(arch: LlmArch) -> bool {
    !matches!(
        arch,
        LlmArch::COGVLM
            | LlmArch::DEEPSEEK4
            | LlmArch::GRANITE_SWITCH
            | LlmArch::EAGLE3
            | LlmArch::DFLASH
            | LlmArch::GEMMA4_ASSISTANT
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arch_names_roundtrip() {
        for &a in LlmArch::ALL {
            if a == LlmArch::UNKNOWN {
                continue; // "(unknown)" parses back to UNKNOWN too, but skip the tautology
            }
            assert_eq!(LlmArch::from_name(a.name()), Some(a), "arch {:?}", a);
        }
    }

    #[test]
    fn arch_from_string_spot_checks() {
        assert_eq!(LlmArch::from_name("qwen2"), Some(LlmArch::QWEN2));
        assert_eq!(LlmArch::from_name("llama"), Some(LlmArch::LLAMA));
        assert_eq!(LlmArch::from_name("gpt-oss"), Some(LlmArch::OPENAI_MOE));
        assert_eq!(LlmArch::from_name("ernie4_5"), Some(LlmArch::ERNIE4_5));
        assert_eq!(LlmArch::from_name("ernie4_5-moe"), Some(LlmArch::ERNIE4_5_MOE));
        assert_eq!(LlmArch::from_name("lfm2"), Some(LlmArch::LFM2));
        assert_eq!(LlmArch::from_name("gemma3"), Some(LlmArch::GEMMA3));
        assert_eq!(LlmArch::from_name("deepseek2"), Some(LlmArch::DEEPSEEK2));
        assert_eq!(LlmArch::from_name("bert"), Some(LlmArch::BERT));
        assert_eq!(LlmArch::from_name("no-such-arch"), None);
    }

    #[test]
    fn kv_names_arch_prefixed_and_fixed() {
        // arch-specific keys take the arch prefix (the documented pitfall)
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::BLOCK_COUNT), "qwen2.block_count");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::ATTENTION_HEAD_COUNT), "qwen2.attention.head_count");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::ROPE_FREQ_BASE), "qwen2.rope.freq_base");
        assert_eq!(kv_name(LlmArch::LLAMA, LlmKv::CONTEXT_LENGTH), "llama.context_length");
        assert_eq!(kv_name(LlmArch::DEEPSEEK2, LlmKv::ATTENTION_KEY_LENGTH_MLA), "deepseek2.attention.key_length_mla");
        // tokenizer/general/split/adapter keys carry NO arch prefix
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::TOKENIZER_MODEL), "tokenizer.ggml.model");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::TOKENIZER_BOS_ID), "tokenizer.ggml.bos_token_id");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::GENERAL_ARCHITECTURE), "general.architecture");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::SPLIT_NO), "split.no");
        assert_eq!(kv_name(LlmArch::QWEN2, LlmKv::ATTENTION_SLIDING_WINDOW), "qwen2.attention.sliding_window");
        assert_eq!(kv_name(LlmArch::GEMMA3, LlmKv::ATTENTION_SLIDING_WINDOW), "gemma3.attention.sliding_window");
    }

    #[test]
    fn tensor_names_block_templates() {
        assert_eq!(tensor_name(LlmTensor::TOKEN_EMBD, -1), "token_embd");
        assert_eq!(tensor_name(LlmTensor::OUTPUT_NORM, -1), "output_norm");
        assert_eq!(tensor_name(LlmTensor::OUTPUT, -1), "output");
        assert_eq!(tensor_name(LlmTensor::ATTN_NORM, 0), "blk.0.attn_norm");
        assert_eq!(tensor_name(LlmTensor::ATTN_NORM, 23), "blk.23.attn_norm");
        assert_eq!(tensor_name(LlmTensor::FFN_GATE, 5), "blk.5.ffn_gate");
        assert_eq!(tensor_name(LlmTensor::FFN_DOWN_EXPS, 3), "blk.3.ffn_down_exps");
        // two-%d template: block id + expert id
        assert_eq!(tensor_name_xid(LlmTensor::FFN_GATE_EXP, 3, 7), "blk.3.ffn_gate.7");
        // suffix variant used all over llama-model.cpp
        assert_eq!(tensor_name_suffix(LlmTensor::TOKEN_EMBD, "weight", -1, -1), "token_embd.weight");
        assert_eq!(tensor_name_suffix(LlmTensor::ATTN_NORM, "weight", 0, -1), "blk.0.attn_norm.weight");
        assert_eq!(tensor_name_suffix(LlmTensor::OUTPUT_NORM, "weight", -1, -1), "output_norm.weight");
        // LFM2 wrong-name fix entry
        assert_eq!(tensor_name(LlmTensor::OUTPUT_NORM_LFM2, -1), "token_embd_norm");
        // dec/enc prefixes (T5)
        assert_eq!(tensor_name(LlmTensor::DEC_ATTN_Q, 2), "dec.blk.2.attn_q");
        // no name in table -> C++ aborts; we panic (untestable via safe API, check template)
        assert_eq!(LlmTensor::SSM_CONV1D.template(), Some("blk.%d.ssm_conv1d"));
    }

    #[test]
    fn arch_classifications() {
        assert!(llm_arch_is_recurrent(LlmArch::MAMBA));
        assert!(!llm_arch_is_recurrent(LlmArch::QWEN2));
        assert!(llm_arch_is_hybrid(LlmArch::LFM2));
        assert!(llm_arch_is_hybrid(LlmArch::QWEN3NEXT));
        assert!(!llm_arch_is_hybrid(LlmArch::QWEN3));
        assert!(llm_arch_is_diffusion(LlmArch::DREAM));
        assert!(!llm_arch_supports_sm_tensor(LlmArch::DEEPSEEK2));
        assert!(llm_arch_supports_sm_tensor(LlmArch::QWEN2));
        assert!(llm_arch_supports_rs_rollback(LlmArch::LFM2));
        assert!(!llm_arch_supports_rs_rollback(LlmArch::QWEN2));
        // tensor buffer-class spot checks from LLM_TENSOR_INFOS
        assert_eq!(LlmTensor::TOKEN_EMBD.layer(), LlmTensorLayer::INPUT);
        assert_eq!(LlmTensor::OUTPUT.layer(), LlmTensorLayer::OUTPUT);
        assert_eq!(LlmTensor::ATTN_NORM.layer(), LlmTensorLayer::REPEATING);
    }

    #[test]
    fn table_sizes_match_reference() {
        // guards against accidental table truncation; update when regenerating
        assert_eq!(LlmArch::ALL.len(), @@ARCH_COUNT@@);
        assert_eq!(count_match_arms(), @@KV_COUNT@@);
    }

    fn count_match_arms() -> usize {
        // count of named LlmKv variants == variants in the enum
        LLM_KV_COUNT
    }

    pub const LLM_KV_COUNT: usize = @@KV_COUNT@@;
}
'''


def main():
    h_text = read(REF / "src/llama-arch.h")
    cpp_text = read(REF / "src/llama-arch.cpp")

    arch_enum = parse_enum(h_text, "llm_arch")
    kv_enum = parse_enum(h_text, "llm_kv")
    tensor_enum = parse_enum(h_text, "llm_tensor")

    arch_names = parse_kv_map(find_map_block(cpp_text, "LLM_ARCH_NAMES"))
    kv_names = parse_kv_map(find_map_block(cpp_text, "LLM_KV_NAMES"))
    tensor_names = parse_kv_map(find_map_block(cpp_text, "LLM_TENSOR_NAMES"))
    tensor_infos = parse_info_map(find_map_block(cpp_text, "LLM_TENSOR_INFOS"))

    # sanity: map keys must be valid enum values
    for key, _ in arch_names:
        assert key in arch_enum, key
    for key, _ in kv_names:
        assert key in kv_enum, key
    for key, _ in tensor_names:
        assert key in tensor_enum, key
    for key, _ in tensor_infos:
        assert key in tensor_enum, key

    body = gen_arch(arch_names, kv_names, tensor_names, tensor_infos, arch_enum, kv_enum, tensor_enum)
    footer = (FOOTER.replace('@@ARCH_COUNT@@', str(len(arch_enum)))
                  .replace('@@KV_COUNT@@', str(len(kv_enum))))
    content = body + footer

    if "--check" in sys.argv:
        current = read(OUT) if OUT.exists() else ""
        if current != content:
            die("arch.rs is out of date — run arch_gen.py")
        print("arch.rs up to date")
        return

    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT} ({len(arch_enum)} archs, {len(kv_enum)} kvs, {len(tensor_enum)} tensors, "
          f"{len(tensor_infos)} tensor-infos)")
    # also run rustfmt for a canonical layout
    subprocess.run(["rustfmt", str(OUT)], check=False)


if __name__ == "__main__":
    main()
