#!/usr/bin/env bash
# dflash_parity.sh — the DFlash/DSpark speculative-draft parity cells
# (PARITY.md's dflash section), following parity/eagle_parity.sh: every
# reference number comes from a *fresh* llama-server's FIRST /completion
# (temperature 0, cache_prompt=false), the port's from the release llama-cli.
#
#   cell (a) trunk-unchanged: the committed stream of
#     `--spec-type draft-dflash / draft-dspark -md draft.gguf` must equal the
#     target's plain greedy stream — on the reference (whose dflash driver
#     taps the target's per-layer inputs, speculative.cpp:1046-1048) and on
#     the port — AND the two sides must agree with each other.
#   cell (b) draft parity: ref spec stream == port spec stream (16/16) plus
#     the drafted/accepted counters (the reference's server-log "draft
#     acceptance" line, server-context.cpp:677-678, vs the port's
#     spec: n_drafted / n_accept lines). The synthetic draft is untrained, so
#     the acceptance is 0 on both sides — the comparable facts are the
#     acceptance RATE (0.00000), the mean accepted length (1.00) and the
#     committed stream; the raw generated counts differ because the two
#     drivers batch verify rounds differently (the server slots vs
#     speculative-simple's whole-round commits).
#
# Both draft variants run — `dflash` (the plain block-diffusion drafter) and
# `dspark` (the Markov + confidence sidecar) — and both FA modes.
#
# usage: bash parity/dflash_parity.sh   (the files are generated by
# `cargo test --release -p llama --test dflash_e2e dflash_write_synth_files -- --ignored`)
set -u

# the reference build of the pinned tree — /home/jeffrey/llm/llama.cpp (the
# llm component matters: /home/jeffrey/llm/llama.cpp does not exist)
REF=/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin
PORT=$(dirname "$0")/../target/release/llama-cli
OUT=/tmp/dflash-parity
mkdir -p $OUT

P='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12'
BODY='{"prompt":"'"$P"'","n_predict":16,"temperature":0,"cache_prompt":false,"return_tokens":true}'

PORT_BASE=${PORT_BASE:-18930}   # fresh port per run, incremented

fail=0

run_ref() { # file log outjson extra...
    local f=$1 log=$2 out=$3; shift 3
    local port=$PORT_BASE; PORT_BASE=$((PORT_BASE + 1))
    $REF/llama-server -m "$f" -c 512 -t 8 --port $port --host 127.0.0.1 "$@" > "$log" 2>&1 &
    local pid=$!
    local ok=""
    for _ in $(seq 1 240); do
        # -f: /health must answer 200 (a 503 "loading" answer is not ready)
        curl -sf "http://127.0.0.1:$port/health" > /dev/null 2>&1 && { ok=1; break; }
        kill -0 $pid 2>/dev/null || break
        sleep 0.5
    done
    if [ -z "$ok" ]; then
        echo "REF SERVER FAILED: $f $*" | tee -a $OUT/errors
        kill $pid 2>/dev/null; wait $pid 2>/dev/null
        fail=1
        return 1
    fi
    curl -s "http://127.0.0.1:$port/completion" -H 'Content-Type: application/json' -d "$BODY" > "$out"
    kill $pid 2>/dev/null; wait $pid 2>/dev/null
    return 0
}

tokens_of() { python3 -c "import json;d=json.load(open('$1'));print(' '.join(map(str,(d.get('tokens') or [])[:16])))"; }

port_run() { # file out extra...
    local f=$1 out=$2; shift 2
    $PORT -m "$f" -p "$P" -n 16 -t 8 "$@" 2>$OUT/port.err > "$out" || {
        echo "PORT RUN FAILED: $f $*" | tee -a $OUT/errors; fail=1; return 1; }
}

# the driver commits whole verify rounds, so the CLI may print n_predict+1
# tokens (speculative-simple.cpp:281) — the comparison takes the first 16
port_tokens_of() { sed -n 's/^gen tokens: \[\(.*\)\]$/\1/p' "$1" | head -1 | tr -d ' ' | tr ',' '\n' | head -16 | tr '\n' ' ' | sed 's/ $//'; }

TGT=/tmp/arch-dflash/llama-synth-dflash-tgt.gguf
[ -f "$TGT" ] || { echo "missing $TGT (run the dflash_write_synth_files generator)" >&2; exit 1; }

# ---- cell (c): the drafted CHAIN — the reference's own speculative-simple
# driver (parity/ref_dflash_chain.cpp over libcommon, the loop of
# examples/speculative-simple.cpp:80-342) vs the port's llama-cli
# (speculative.rs's port of the same loop), both with their SPC_DBG candidate
# traces on: same candidate count and the same (id, p) tuples position for
# position. The server-driver cells (a)/(b) cannot see the drafted ids (the
# untrained draft's acceptance is 0), so this is the direct draft-graph
# oracle. The port's traces print the C's pos convention (i-1 for DFlash,
# speculative.cpp:1304; i for DSpark, :1284).
CHAIN=$(dirname "$0")/../target/release/ref_dflash_chain
if [ ! -x "$CHAIN" ]; then
    g++ -O2 -std=c++17 "$(dirname "$0")/ref_dflash_chain.cpp" -o "$CHAIN" \
        -I /home/jeffrey/llm/llama.cpp-pinned/include \
        -I /home/jeffrey/llm/llama.cpp-pinned/ggml/include \
        -I /home/jeffrey/llm/llama.cpp-pinned/common \
        -L $REF -lllama -lllama-common -Wl,-rpath,$REF || {
        echo "CHAIN PROBE BUILD FAILED" | tee -a $OUT/errors; fail=1; }
fi
if [ -x "$CHAIN" ]; then
    for kind in dflash dspark; do
        DRAFT=/tmp/arch-dflash/dflash-synth-$kind.gguf
        LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-$kind 16 2>$OUT/$kind-chain-ref.err \
            | grep -E "^spec:" > $OUT/$kind-chain-ref.txt || fail=1
        LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-$kind 16 2>&1 >/dev/null \
            | grep -o "draft candidate *[0-9]*, pos *[0-9]*: *[0-9]* *( *[0-9.-]*)" | sed 's/  */ /g' \
            > $OUT/$kind-chain-ref-cand.txt
        LLAMA_SPEC_VERBOSE=1 $PORT -m "$TGT" -md "$DRAFT" --spec-type draft-$kind \
            --spec-draft-n-max 3 -fa off -p "$P" -n 16 -t 8 2>&1 >/dev/null \
            | grep -o "draft candidate *[0-9]*, pos *[0-9]*: *[0-9]* *( *[0-9.-]*)" | sed 's/  */ /g' \
            > $OUT/$kind-chain-port-cand.txt
        n_ref=$(wc -l < $OUT/$kind-chain-ref-cand.txt)
        n_port=$(wc -l < $OUT/$kind-chain-port-cand.txt)
        if [ "$n_ref" = "$n_port" ] && cmp -s $OUT/$kind-chain-ref-cand.txt $OUT/$kind-chain-port-cand.txt; then
            echo "  (c) $kind chain: $n_port candidate lines, ref == port id/p per position PASS"
        else
            echo "  (c) $kind chain FAIL (ref {n_ref} vs port {n_port} candidate lines)"
            diff $OUT/$kind-chain-ref-cand.txt $OUT/$kind-chain-port-cand.txt | head -6 | sed 's/^/    /'
            fail=1
        fi
    done
    # the DSV4 DSpark chain — the full deepseek4-stage draft's candidates
    if [ -f /tmp/arch-dflash/dflash-synth-dspark-dsv4.gguf ]; then
        kind=dspark-dsv4
        DRAFT=/tmp/arch-dflash/dflash-synth-$kind.gguf
        LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-dspark 16 2>&1 >/dev/null \
            | grep -o "draft candidate *[0-9]*, pos *[0-9]*: *[0-9]* *( *[0-9.-]*)" | sed 's/  */ /g' \
            > $OUT/$kind-chain-ref-cand.txt
        LLAMA_SPEC_VERBOSE=1 $PORT -m "$TGT" -md "$DRAFT" --spec-type draft-dspark \
            --spec-draft-n-max 3 -fa off -p "$P" -n 16 -t 8 2>&1 >/dev/null \
            | grep -o "draft candidate *[0-9]*, pos *[0-9]*: *[0-9]* *( *[0-9.-]*)" | sed 's/  */ /g' \
            > $OUT/$kind-chain-port-cand.txt
        n_ref=$(wc -l < $OUT/$kind-chain-ref-cand.txt)
        n_port=$(wc -l < $OUT/$kind-chain-port-cand.txt)
        if [ "$n_ref" = "$n_port" ] && cmp -s $OUT/$kind-chain-ref-cand.txt $OUT/$kind-chain-port-cand.txt; then
            echo "  (c) $kind chain: $n_port candidate lines, ref == port id/p per position PASS"
        else
            echo "  (c) $kind chain FAIL (ref {n_ref} vs port {n_port} candidate lines)"
            diff $OUT/$kind-chain-ref-cand.txt $OUT/$kind-chain-port-cand.txt | head -6 | sed 's/^/    /'
            fail=1
        fi
    fi
    # the DFlash2 chain — the selector path prints no candidates; the walked
    # drafts (the lattice walk output) are the comparable trace
    if [ -f /tmp/arch-dflash/dflash-synth-dflash2.gguf ]; then
        kind=dflash2
        DRAFT=/tmp/arch-dflash/dflash-synth-$kind.gguf
        LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-dflash 16 2>/dev/null \
            | grep -o "^round_draft:.*" > $OUT/$kind-chain-ref.txt
        LLAMA_SPEC_VERBOSE=1 $PORT -m "$TGT" -md "$DRAFT" --spec-type draft-dflash \
            --spec-draft-n-max 3 -fa off -p "$P" -n 16 -t 8 2>&1 >/dev/null \
            | grep -o "round draft: .*" | sed -e 's/^round draft:/round_draft:/' -e 's/\[//' -e 's/\]//' -e 's/,/ /g' -e 's/  */ /g' \
            > $OUT/$kind-chain-port.txt
        n_ref=$(wc -l < $OUT/$kind-chain-ref.txt)
        n_port=$(wc -l < $OUT/$kind-chain-port.txt)
        if [ "$n_ref" = "$n_port" ] && cmp -s $OUT/$kind-chain-ref.txt $OUT/$kind-chain-port.txt; then
            echo "  (c) $kind chain: $n_port walked-draft rounds, ref == port PASS"
        else
            echo "  (c) $kind chain FAIL (ref {n_ref} vs port {n_port} rounds)"
            diff $OUT/$kind-chain-ref.txt $OUT/$kind-chain-port.txt | head -6 | sed 's/^/    /'
            fail=1
        fi
    fi
fi

# ---- cell (d): the DFlash2 / DSV4-DSpark dump-first differentials — the
# port's #[ignore] dump tests vs parity/ref_dflash_chain.cpp --dump-first at
# CHAIN_FA=on (the v_trans = 0 layout): the DSV4 injected ring state must be
# byte-identical; the DFlash2 first noise block's logits + selector lattice
# within FP ulps with the lattice's candidate-id head exact
if [ -x "$CHAIN" ]; then
    DRAFT=/tmp/arch-dflash/dflash-synth-dspark-dsv4.gguf
    if [ -f "$DRAFT" ]; then
        DUMP_STATE_OUT=/tmp/arch-dflash/ref-dsv4-state.bin CHAIN_FA=on \
            LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-dspark 16 --dump-first \
            > /tmp/arch-dflash/ref-dump-first-dspark-dsv4.txt 2>/dev/null
        cargo test --release -p llama --test dflash_e2e dspark_dsv4_dump_first -- --ignored --nocapture \
            > $OUT/dump-dsv4.log 2>&1
        if grep -aq "byte-identical to the reference" $OUT/dump-dsv4.log; then
            echo "  (d) dspark-dsv4 injected ring state: port == reference, byte-identical PASS"
        else
            echo "  (d) dspark-dsv4 injected ring state FAIL"; tail -5 $OUT/dump-dsv4.log | sed 's/^/    /'; fail=1
        fi
    fi
    DRAFT=/tmp/arch-dflash/dflash-synth-dflash2.gguf
    if [ -f "$DRAFT" ]; then
        CHAIN_FA=on LLAMA_LOG_LEVEL=error "$CHAIN" "$TGT" "$DRAFT" draft-dflash 16 --dump-first \
            > /tmp/arch-dflash/ref-dump-first-dflash2.txt 2>/dev/null
        cargo test --release -p llama --test dflash_e2e dflash2_dump_first -- --ignored --nocapture \
            > $OUT/dump-dflash2.log 2>&1
        if grep -aq "ids exact" $OUT/dump-dflash2.log; then
            echo "  (d) dflash2 first noise block + selector lattice: within FP ulps, candidate ids exact PASS"
        else
            echo "  (d) dflash2 dump-first FAIL"; tail -5 $OUT/dump-dflash2.log | sed 's/^/    /'; fail=1
        fi
    fi
fi

for kind in dflash dspark dspark-dsv4 dflash2; do
    DRAFT=/tmp/arch-dflash/dflash-synth-$kind.gguf
    [ -f "$DRAFT" ] || { echo "missing $DRAFT (run the dflash_write_synth_files generator)" >&2; exit 1; }
    # the DFlash2 draft selects the plain draft-dflash type (no markov head)
    SPEC_TYPE="draft-$kind"
    if [ "$kind" = dflash2 ]; then SPEC_TYPE="draft-dflash"; fi
    if [ "$kind" = dspark-dsv4 ]; then SPEC_TYPE="draft-dspark"; fi

    for fa in off on; do
        echo "=== $kind fa=$fa ==="

        # ---- cell (a): trunk-unchanged (the committed stream == plain) ----
        run_ref "$TGT" $OUT/$kind-$fa-plain.log $OUT/$kind-$fa-plain.json -fa $fa || continue
        run_ref "$TGT" $OUT/$kind-$fa-spec.log $OUT/$kind-$fa-spec.json -fa $fa \
            -md "$DRAFT" --spec-type $SPEC_TYPE --spec-draft-n-max 3 || continue
        T_PLAIN=$(tokens_of $OUT/$kind-$fa-plain.json)
        T_SPEC=$(tokens_of $OUT/$kind-$fa-spec.json)

        port_run "$TGT" $OUT/$kind-$fa-port-plain.txt -fa $fa || continue
        port_run "$TGT" $OUT/$kind-$fa-port-spec.txt -fa $fa \
            -md "$DRAFT" --spec-type $SPEC_TYPE --spec-draft-n-max 3 || continue
        P_PLAIN=$(port_tokens_of $OUT/$kind-$fa-port-plain.txt)
        P_SPEC=$(port_tokens_of $OUT/$kind-$fa-port-spec.txt)

        n_ref=$(echo $T_PLAIN | wc -w); n_port=$(echo $P_PLAIN | wc -w)
        if [ "$T_PLAIN" = "$T_SPEC" ] && [ "$T_PLAIN" = "$P_PLAIN" ] && [ "$P_PLAIN" = "$P_SPEC" ] \
           && [ "$n_ref" -ge 16 ] && [ "$n_port" -ge 16 ]; then
            echo "  (a) trunk-unchanged: ref plain==ref spec==port plain==port spec == [$T_PLAIN ...] PASS"
        else
            echo "  (a) trunk-unchanged FAIL"
            echo "    ref plain : $T_PLAIN"
            echo "    ref spec  : $T_SPEC"
            echo "    port plain: $P_PLAIN"
            echo "    port spec : $P_SPEC"
            fail=1
        fi

        # ---- cell (b): draft parity ----
        # the reference's per-slot "draft acceptance" line (server-context.cpp
        # :677-678) and the port's spec: counters — the RATE and mean length
        # are the comparable facts (the raw counts differ: the server slots
        # batch verify rounds differently than speculative-simple commits)
        REF_ACC=$(grep -o "draft acceptance.*" $OUT/$kind-$fa-spec.log | tail -1)
        REF_RATE=$(echo "$REF_ACC" | sed -n 's/draft acceptance = \([0-9.]*\).*/\1/p')
        REF_MEAN=$(echo "$REF_ACC" | sed -n 's/.*mean len = *\([0-9.]*\)/\1/p')
        PORT_DRAFTED=$(grep -o "spec: n_drafted = [0-9]*" $OUT/$kind-$fa-port-spec.txt | grep -o '[0-9]*')
        PORT_ACCEPT=$(grep -o "spec: n_accept  = [0-9]*" $OUT/$kind-$fa-port-spec.txt | grep -o '[0-9]*')
        PORT_RATE=$(python3 -c "d=$PORT_DRAFTED; a=$PORT_ACCEPT; print(f'{100.0*a/d:.5f}' if d else '0.00000')")

        if [ -n "$T_SPEC" ] && [ "$T_SPEC" = "$P_SPEC" ] \
           && [ "$REF_RATE" = "$PORT_RATE" ]; then
            echo "  (b) draft parity: ref spec stream == port spec stream (16/16), accept rate $REF_RATE == $PORT_RATE PASS"
            echo "      ref  : $REF_ACC"
            echo "      port : drafted $PORT_DRAFTED, accepted $PORT_ACCEPT (rate $PORT_RATE)"
        else
            echo "  (b) draft parity FAIL"
            echo "    ref stream : $T_SPEC"
            echo "    port stream: $P_SPEC"
            echo "    ref  : $REF_ACC"
            echo "    port : drafted $PORT_DRAFTED, accepted $PORT_ACCEPT (rate $PORT_RATE)"
            fail=1
        fi
    done
done

if [ $fail -eq 0 ]; then
    echo "ALL DFLASH PARITY CELLS PASS"
else
    echo "DFLASH PARITY FAILURES — see $OUT"
fi
exit $fail
