#!/usr/bin/env bash
# eagle_parity.sh — the EAGLE3 speculative-draft parity cells (PARITY.md's
# eagle3 section), following parity/mtp_parity.sh: every reference number
# comes from a *fresh* llama-server's FIRST /completion (temperature 0,
# cache_prompt=false), the port's from the release llama-cli.
#
#   cell (a) trunk-unchanged: the committed stream of
#     `--spec-type draft-eagle3 -md head.gguf` must equal the target's plain
#     greedy stream — on the reference (whose eagle3 driver taps the target's
#     per-layer inputs, llama.cpp:127 + speculative.cpp:513-522) and on the
#     port — AND the two sides must agree with each other.
#   cell (b) draft parity: ref spec stream == port spec stream (16/16) plus
#     the drafted/accepted counters (the reference's server-log "draft
#     acceptance" line, server-context.cpp:677-678, vs the port's
#     spec: n_drafted / n_accept lines).
#
# Both head variants run — `own` (head carries token_embd + output) and
# `other` (they come from the target through ctx_other /
# eagle.rs's external-storage tensors) — and both FA modes.
#
# usage: bash parity/eagle_parity.sh [-long]   (the files are generated by
# `cargo test --release -p llama --test eagle_e2e eagle_write_synth_files -- --ignored`)
set -u

# the reference build of the pinned tree — /home/jeffrey/llm/llama.cpp (the
# llm component matters: /home/jeffrey/llama.cpp does not exist)
REF=/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin
PORT=$(dirname "$0")/../target/release/llama-cli
OUT=/tmp/eagle-parity
mkdir -p $OUT

P='1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12'
BODY='{"prompt":"'"$P"'","n_predict":16,"temperature":0,"cache_prompt":false,"return_tokens":true}'

PORT_BASE=${PORT_BASE:-18880}   # fresh port per run, incremented

fail=0

run_ref() { # file log outjson extra...
    local f=$1 log=$2 out=$3; shift 3
    local port=$PORT_BASE; PORT_BASE=$((PORT_BASE + 1))
    $REF/llama-server -m "$f" -c 512 -t 8 --port $port --host 127.0.0.1 "$@" > "$log" 2>&1 &
    local pid=$!
    local ok=""
    for _ in $(seq 1 240); do
        curl -s "http://127.0.0.1:$port/health" > /dev/null 2>&1 && { ok=1; break; }
        kill -0 $pid 2>/dev/null || break
        sleep 0.5
    done
    if [ -z "$ok" ]; then
        echo "REF SERVER FAILED: $f $*" | tee -a $OUT/errors
        kill $pid 2>/dev/null; wait $pid 2>/dev/null
        fail=1
        return 1
    fi
    curl -s "http://127.0.0.1:$port/completion" -H 'Content-Type: application/json' -d "$BODY" > "$out"
    kill $pid 2>/dev/null; wait $pid 2>/dev/null
    return 0
}

tokens_of() { python3 -c "import json;d=json.load(open('$1'));print(' '.join(map(str,(d.get('tokens') or [])[:16])))"; }

port_run() { # file out extra...
    local f=$1 out=$2; shift 2
    $PORT -m "$f" -p "$P" -n 16 -t 8 "$@" 2>$OUT/port.err > "$out" || {
        echo "PORT RUN FAILED: $f $*" | tee -a $OUT/errors; fail=1; return 1; }
}

# the driver commits whole verify rounds, so the CLI may print n_predict+1
# tokens (speculative-simple.cpp:281) — the comparison takes the first 16
port_tokens_of() { sed -n 's/^gen tokens: \[\(.*\)\]$/\1/p' "$1" | head -1 | tr -d ' ' | tr ',' '\n' | head -16 | tr '\n' ' ' | sed 's/ $//'; }

TGT=/tmp/arch-eagle/llama-synth-eagle-tgt.gguf
[ -f "$TGT" ] || { echo "missing $TGT (run the eagle_write_synth_files generator)" >&2; exit 1; }

for kind in own other; do
    HEAD=/tmp/arch-eagle/eagle3-synth-$kind.gguf
    [ -f "$HEAD" ] || { echo "missing $HEAD (run the eagle_write_synth_files generator)" >&2; exit 1; }

    for fa in off on; do
        echo "=== head=$kind fa=$fa ==="

        # ---- cell (a): trunk-unchanged (the committed stream == plain) ----
        run_ref "$TGT" $OUT/$kind-$fa-plain.log $OUT/$kind-$fa-plain.json -fa $fa || continue
        run_ref "$TGT" $OUT/$kind-$fa-spec.log $OUT/$kind-$fa-spec.json -fa $fa \
            -md "$HEAD" --spec-type draft-eagle3 --spec-draft-n-max 3 || continue
        T_PLAIN=$(tokens_of $OUT/$kind-$fa-plain.json)
        T_SPEC=$(tokens_of $OUT/$kind-$fa-spec.json)

        port_run "$TGT" $OUT/$kind-$fa-port-plain.txt -fa $fa || continue
        port_run "$TGT" $OUT/$kind-$fa-port-spec.txt -fa $fa -md "$HEAD" \
            --spec-type draft-eagle3 --spec-draft-n-max 3 || continue
        P_PLAIN=$(port_tokens_of $OUT/$kind-$fa-port-plain.txt)
        P_SPEC=$(port_tokens_of $OUT/$kind-$fa-port-spec.txt)

        n_ref=$(echo $T_PLAIN | wc -w); n_port=$(echo $P_PLAIN | wc -w)
        if [ "$T_PLAIN" = "$T_SPEC" ] && [ "$T_PLAIN" = "$P_PLAIN" ] && [ "$P_PLAIN" = "$P_SPEC" ] \
           && [ "$n_ref" -ge 16 ] && [ "$n_port" -ge 16 ]; then
            echo "  (a) trunk-unchanged: ref plain==ref spec==port plain==port spec == [$T_PLAIN ...] PASS"
        else
            echo "  (a) trunk-unchanged FAIL"
            echo "    ref plain : $T_PLAIN"
            echo "    ref spec  : $T_SPEC"
            echo "    port plain: $P_PLAIN"
            echo "    port spec : $P_SPEC"
            fail=1
        fi

        # ---- cell (b): draft parity (ref spec == port spec, 16/16) ----
        REF_ACC=$(grep -aoE "draft acceptance = [0-9.]+ \([[:space:]]*[0-9]+ accepted / *[0-9]+ generated\), mean len =  *[0-9.]+" \
            $OUT/$kind-$fa-spec.log | tail -1)
        PORT_DRAFTED=$(grep -o "spec: n_drafted = [0-9]*" $OUT/$kind-$fa-port-spec.txt | grep -o '[0-9]*')
        PORT_ACCEPT=$(grep -o "spec: n_accept  = [0-9]*" $OUT/$kind-$fa-port-spec.txt | grep -o '[0-9]*')

        if [ -n "$T_SPEC" ] && [ "$T_SPEC" = "$P_SPEC" ]; then
            echo "  (b) draft parity: ref spec stream == port spec stream (16/16) PASS"
            echo "      ref  : $REF_ACC"
            echo "      port : drafted $PORT_DRAFTED, accepted $PORT_ACCEPT"
        else
            n_same=$(python3 -c "
a = '$T_SPEC'.split(); b = '$P_SPEC'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
            n_tot=$(python3 -c "print(len('$T_SPEC'.split()))")
            # like the MTP cells: with a random-weight head the acceptance is
            # ~0 and the draft chain (which feeds its own prenorm rows back
            # through encoder+decoder) is a chaotic amplifier — the structural
            # requirement is prefix agreement through several full head
            # evaluations (the committed stream itself is cell (a))
            need=16
            if [ "$n_same" -ge "$need" ]; then
                echo "  (b) draft parity: $n_same/$n_tot identical (need >= $need) —"
                echo "      beyond that the random-head chain is a chaotic amplifier (see header)"
                echo "    ref  spec: $T_SPEC"
                echo "    port spec: $P_SPEC"
            else
                echo "  (b) draft parity FAIL"
                echo "    ref  spec: $T_SPEC"
                echo "    port spec: $P_SPEC"
                echo "    ref  acc : $REF_ACC"
                echo "    port acc : drafted $PORT_DRAFTED accepted $PORT_ACCEPT"
                fail=1
            fi
            echo "    ref  acc : $REF_ACC"
            echo "    port acc : drafted $PORT_DRAFTED accepted $PORT_ACCEPT"
        fi
    done
done

echo
if [ $fail -eq 0 ]; then
    echo "EAGLE3 PARITY: ALL CELLS PASS"
else
    echo "EAGLE3 PARITY: FAILURES (see above)"
fi
exit $fail
