#!/usr/bin/env python3
"""gen_ui_assets.py — the port's counterpart of scripts/ui-assets.cmake's
`emit_files` (llama.cpp bd4f514db1, lines 143-269): embed a provisioned UI
dist tree into the server binary as a generated Rust source.

The reference's provisioning priority (tools/ui/CMakeLists.txt + the cmake
script): a pre-built `tools/ui/dist` > an npm build > an HF bucket download;
whatever lands in `dist/` becomes `ui.cpp`/`ui.h` — one byte array per file,
gzip-compressed with a ZEROED timestamp when LLAMA_UI_GZIP (the default) so
identical inputs give identical bytes and stable ETags (:176-181/:204-219),
a quoted SHA-256 ETag per embedded file (:234-245), and the extension→MIME
table of `mime_from_ext` (:17-60). An empty tree (no index.html) emits an
EMPTY table (:150-159) — exactly the checked-in state of
crates/tools/llama-server/src/ui_assets.rs, which matches this machine's
reference build (build-rust-ref/tools/ui/ui.cpp embeds 0 assets).

This script plays the same role for the port: it walks a dist tree, gzips
with mtime=0, SHA-256-ETags, maps mimes, validates the required asset set
(`ui_validate_assets`, :68-141), and regenerates ui_assets.rs. Serving
semantics live in crates/tools/llama-server/src/ui.rs (server-http.cpp:
360-478).

usage: gen_ui_assets.py [dist_dir]
  default dist_dir: crates/tools/llama-server/ui-dist
"""

import gzip
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DIST = os.path.join(HERE, "..", "crates", "tools", "llama-server", "ui-dist")
OUT = os.path.join(HERE, "..", "crates", "tools", "llama-server", "src", "ui_assets.rs")

# LLAMA_UI_GZIP's default is ON (tools/ui/CMakeLists.txt:4)
USE_GZIP = True

# mime_from_ext (scripts/ui-assets.cmake:19-58)
MIME = {
    "html": "text/html; charset=utf-8",
    "css": "text/css",
    "js": "application/javascript",
    "json": "application/json",
    "webmanifest": "application/manifest+json",
    "svg": "image/svg+xml",
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "ico": "image/x-icon",
    "woff": "font/woff",
    "woff2": "font/woff2",
}


def mime_from_ext(name: str) -> str:
    ext = name.rsplit(".", 1)[1] if "." in name else ""
    return MIME.get(ext, "application/octet-stream")


def validate(assets):
    """ui_validate_assets (scripts/ui-assets.cmake:68-141)"""
    import re

    names = [os.path.basename(a) for a in assets]
    required = {
        "index.html": any(n == "index.html" for n in names),
        "manifest.webmanifest": any(n == "manifest.webmanifest" for n in names),
        "sw.js": any(n == "sw.js" for n in names),
        "build.json": any(n == "build.json" for n in names),
        "version.json": any(n == "version.json" for n in names),
        "bundle[hash].js": any(re.match(r"^bundle.*\.js$", n) for n in names),
        "bundle[hash].css": any(re.match(r"^bundle.*\.css$", n) for n in names),
        "workbox[hash].js": any(re.match(r"^workbox.*\.js$", n) for n in names),
    }
    missing = [k for k, ok in required.items() if not ok]
    if missing:
        sys.exit(
            "UI: missing required asset(s):\n    "
            + "\n    ".join(missing)
            + "\nUI: current asset files:\n    "
            + "\n    ".join(assets)
        )


def emit(dist_dir: str):
    # the asset list (scripts/ui-assets.cmake:150-159): everything under the
    # tree when index.html exists, else an EMPTY table
    assets = []
    if os.path.exists(os.path.join(dist_dir, "index.html")):
        for root, _dirs, files in os.walk(dist_dir):
            for f in files:
                full = os.path.join(root, f)
                rel = os.path.relpath(full, dist_dir)
                if rel.startswith("_gzip/"):
                    continue
                assets.append(rel)
        assets.sort()

    if assets:
        validate(assets)

    lines = [
        "// Generated by parity/gen_ui_assets.py — do not edit.",
        "// (the port's counterpart of build-rust-ref/tools/ui/ui.cpp, which is",
        "// generated by scripts/ui-assets.cmake from a provisioned dist tree — an",
        "// empty table when none was provisioned, exactly this file's state.)",
        "//",
        f"// Regenerate after dropping a built UI dist at",
        f"// crates/tools/llama-server/ui-dist/ with:",
        "//     python3 parity/gen_ui_assets.py",
        "",
        "use super::ui::UiAsset;",
        "",
        f"pub const USE_GZIP: bool = {str(USE_GZIP).lower()};",
        "",
    ]

    if not assets:
        lines.append("pub const ASSETS: &[UiAsset] = &[];")
        open(OUT, "w").write("\n".join(lines) + "\n")
        print(f"UI: embedded 0 assets (empty table, {dist_dir} has no index.html)")
        return

    # gzip with a zeroed header timestamp for stable bytes/ETags
    # (SOURCE_DATE_EPOCH=0 + file(ARCHIVE_CREATE ... COMPRESSION GZip))
    rows = []
    arrs = []
    for i, rel in enumerate(assets):
        with open(os.path.join(dist_dir, rel), "rb") as f:
            raw = f.read()
        if not raw:
            sys.exit(f"UI: empty file: {rel}")
        data = gzip.compress(raw, mtime=0) if USE_GZIP else raw
        etag = hashlib.sha256(data).hexdigest()
        rows.append(
            f'    UiAsset {{ name: "{rel}", data: &ASSET_{i}, etag: "\\"{etag}\\"", ty: "{mime_from_ext(rel)}" }},'
        )
        hexs = data.hex()
        arrs.append(
            "static ASSET_%d: &[u8] = &[%s];" % (i, ",".join("0x%s" % hexs[j:j+2] for j in range(0, len(hexs), 2)))
        )

    body = "\n".join(arrs) + '\n\npub const ASSETS: &[UiAsset] = &[\n' + "\n".join(rows) + "\n];\n"
    open(OUT, "w").write("\n".join(lines) + "\n" + body)
    print(f"UI: embedded {len(assets)} assets (gzip={USE_GZIP}) -> {os.path.relpath(OUT)}")


if __name__ == "__main__":
    dist = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DIST
    emit(dist)
