#!/usr/bin/env bash
# gptoss_server_check.sh — gpt-oss channel-format end-to-end vs the reference
# llama-server (agent: specialized chat parsers + audio mtmd).
#
# 1. starts the pinned reference llama-server with the local gpt-oss-20b
#    (CPU, temperature 0)
# 2. renders the exact chat prompt for the same request through the reference
#    library probe (real template from /props, pinned TZ=UTC)
# 3. captures:
#      - the reference's parsed /v1/chat/completions answer
#        (reasoning_content / content / tool_calls split)
#      - the raw generated bytes (a /completion replay of the rendered prompt)
#      - the reference's rendered prompt and generation prompt
# 4. the port (chat_parsers.rs gpt-oss handler) parses the raw bytes with the
#    same generation prompt; the test asserts the split matches
#    (tests/chat_parsers_gptoss.rs)
#
# Artifacts: /tmp/gptoss-srv/{props.json,probe-cases.json,probe-ref.json,
#                            request.json,response.json,prompt.txt,gen-prompt.txt,
#                            raw-completion.json}
set -euo pipefail

MODEL="${MODEL:-/home/jeffrey/.lmstudio/models/lmstudio-community/gpt-oss-20b-GGUF/gpt-oss-20b-MXFP4.gguf}"
REF="${REF:-/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin}"
PORT="${PORT:-8183}"
OUT="${OUT:-/tmp/gptoss-srv}"
mkdir -p "$OUT"
cd "$(dirname "$0")/.."

# never pkill a pattern contained in this command line itself — match the port
bash parity/kill_stale_servers.sh "$PORT" || true
sleep 1

export TZ=UTC
nohup "$REF/llama-server" -m "$MODEL" -c 4096 -t "$(nproc)" --temp 0 --port "$PORT" \
    --host 127.0.0.1 --jinja >"$OUT/server.log" 2>&1 &

for i in $(seq 1 300); do
  if curl -s "http://127.0.0.1:$PORT/health" | grep -q '"ok"'; then break; fi
  sleep 2
done
curl -s "http://127.0.0.1:$PORT/health" | grep -q '"ok"' || { echo "server failed to start"; tail -5 "$OUT/server.log"; exit 1; }

curl -s "http://127.0.0.1:$PORT/props" >"$OUT/props.json"

# render the reference prompt via the library probe (same engine the server
# uses; the pinned clock only affects the date strings, same day either way)
python3 - "$OUT" <<'EOF'
import json, sys
out = sys.argv[1]
props = json.load(open(f"{out}/props.json"))
tmpl = props["default_generation_settings"].get("chat_template") or props.get("chat_template")
assert tmpl and "<|channel|>" in tmpl, "gpt-oss template not found in /props"
messages = [{"role": "user", "content": "What is the weather in Tokyo right now? Use the tool."}]
tools = [{"type": "function", "function": {
    "name": "get_weather", "description": "Get the current weather for a city",
    "parameters": {"type": "object",
                   "properties": {"city": {"type": "string"}, "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]}},
                   "required": ["city"]}}}]
case = {"template": "gptoss", "messages": messages, "tools": tools,
        "tool_choice": "auto", "parallel_tool_calls": False,
        "add_generation_prompt": True, "reasoning_format": "deepseek"}
json.dump({"templates": [{"name": "gptoss", "src": tmpl}], "cases": [case]},
          open(f"{out}/probe-cases.json", "w"))
json.dump({"messages": messages, "tools": tools, "tool_choice": "auto",
           "temperature": 0, "max_tokens": 256, "stream": False},
          open(f"{out}/request.json", "w"))
EOF

TZ=UTC ./parity/ref_chat_tools_dump "$OUT/probe-cases.json" "$OUT/probe-ref.json" 2>/dev/null
python3 - "$OUT" <<'EOF'
import json, sys
out = sys.argv[1]
r = json.load(open(f"{out}/probe-ref.json"))[0]
assert r.get("ok"), r.get("error")
open(f"{out}/prompt.txt", "w").write(r["prompt"])
open(f"{out}/gen-prompt.txt", "w").write(r["generation_prompt"])
print("reference prompt tail:", repr(r["prompt"][-120:]))
print("reference generation_prompt:", repr(r["generation_prompt"]))
EOF

# 1) the parsed chat answer (the reference does the reasoning/final split)
curl -s "http://127.0.0.1:$PORT/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d @"$OUT/request.json" >"$OUT/response.json"

# 2) the raw bytes the model produced for the same rendered prompt
python3 - "$OUT" <<'EOF'
import json, sys
out = sys.argv[1]
prompt = open(f"{out}/prompt.txt").read()
json.dump({"prompt": prompt, "temperature": 0, "max_tokens": 256, "stream": False},
          open(f"{out}/raw-request.json", "w"))
EOF
curl -s "http://127.0.0.1:$PORT/completion" \
    -H 'Content-Type: application/json' \
    -d @"$OUT/raw-request.json" >"$OUT/raw-completion.json"

bash parity/kill_stale_servers.sh "$PORT" || true

python3 - "$OUT" <<'EOF'
import json, sys
out = sys.argv[1]
resp = json.load(open(f"{out}/response.json"))
msg = resp["choices"][0]["message"]
print("reference reasoning_content:", json.dumps(msg.get("reasoning_content"), ensure_ascii=False)[:200])
print("reference content:", json.dumps(msg.get("content"), ensure_ascii=False)[:200])
print("reference tool_calls:", json.dumps(msg.get("tool_calls"), ensure_ascii=False)[:200])
print("finish_reason:", resp["choices"][0].get("finish_reason"))
raw = json.load(open(f"{out}/raw-completion.json"))
print("raw text:", json.dumps(raw.get("content"), ensure_ascii=False)[:400])
assert raw.get("content"), "no raw completion captured"
EOF
echo "artifacts in $OUT (consumed by tests/chat_parsers_gptoss.rs)"
