#!/usr/bin/env bash
# mtp2_parity.sh — the MTP batch-18 driver-level parity cells: the nine
# GLM4-style graph_mtp heads (qwen35/qwen35moe/qwen3next/glm4moe/cohere2moe/
# bailingmoe3/hy_v3/mimo2/step35) driven end-to-end (`--spec-type draft-mtp`,
# MtpForward + DecodeContext::new_mtp in context.rs), following the
# mtp_parity.sh protocol — every reference number from a fresh llama-server's
# FIRST /completion (temperature 0, cache_prompt=false), the port's from the
# release llama-cli.
#
#   cell (a) stream parity: ref plain == ref spec == port plain == port spec
#     (16 greedy tokens) — the reference's own committed stream is the
#     baseline for both drivers, and the port's plain/spec pair is the
#     self-consistency half (tests/mtp2_e2e.rs mtp2_speculation_matches_
#     plain_greedy pins the same in-repo).
#   cell (b) counters: the ref server-log "draft acceptance" line vs the
#     port's "spec: n_drafted/n_accept" (the semantics differ — the server
#     batches slots, speculative-simple commits whole rounds — the comparable
#     facts are the acceptance rate and the streams).
#
# The four hybrid-loader archs (qwen35 qwen35moe qwen3next bailingmoe3) ABORT
# the pinned reference's own trunk decode (llm_graph_input_mem_hybrid::
# set_input → ggml-backend.cpp:205 GGML_ASSERT(buffer) — the synthetic's
# all-zero recurrent_layers array leaves the hybrid memory's input tensor
# bufferless), so for them the script only RECORDS the abort and the port
# self-consistency cell stands as the driver-level evidence (plus the
# graph-level byte-compare of gen_mtp2_ref.sh).
#
# usage: ./parity/limited.sh -- bash parity/mtp2_parity.sh   (the files are
# generated by `cargo test --release -p llama --test mtp2_e2e mtp2_write_synth_files -- --ignored`)
#
# python-audit (2026-10-01, after the 00:01-00:05 43.4 GiB python3 OOM — the
# burst came AFTER this script's own outputs were all written at 00:00, so an
# ad-hoc uncapped python, not a script step, but every step is bounded anyway):
#   * tokens_of: json.load of one /completion response — n_predict=16, so the
#     file is ~2-3 KB (checked: the largest in /tmp/mtp2-parity is 1984 B);
#   * the three n_* one-liners: compare two 16-token shell strings (~100 B);
#   * no numpy, no whole-file reads of the graph dumps, no accumulation
#     across loop iterations — every python3 here dies below 20 MB RSS.
#   * run_ref now goes through parity/limited.sh like everything else, so the
#     reference server is MemoryMax-bounded too (it was the last uncapped
#     process this script spawned).
set -u

REF=/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin/llama-server
PORT=$(dirname "$0")/../target/release/llama-cli
OUT=/tmp/mtp2-parity
mkdir -p $OUT

P='1, 2, 3, 4, 5, 6'
BODY='{"prompt":"'$P'","n_predict":16,"temperature":0,"cache_prompt":false,"return_tokens":true}'

PORT_BASE=${PORT_BASE:-18870}   # fresh port per run, incremented

fail=0

run_ref() { # file log outjson extra...
    local f=$1 log=$2 out=$3; shift 3
    local port=$PORT_BASE; PORT_BASE=$((PORT_BASE + 1))
    bash "$(dirname "$0")"/limited.sh -- \
        $REF -m "$f" -c 512 -t 8 --port $port --host 127.0.0.1 "$@" > "$log" 2>&1 &
    local pid=$!
    local ok=""
    for _ in $(seq 1 240); do
        # -f: /health answers 503 while the model is still loading
        curl -sf "http://127.0.0.1:$port/health" > /dev/null 2>&1 && { ok=1; break; }
        kill -0 $pid 2>/dev/null || break
        sleep 0.5
    done
    if [ -z "$ok" ]; then
        # $pid is the limited.sh wrapper (exec'd into systemd-run --scope);
        # kill the server child too or the port stays held
        kill $pid 2>/dev/null; pkill -P $pid 2>/dev/null; wait $pid 2>/dev/null
        return 1
    fi
    curl -s "http://127.0.0.1:$port/completion" -H 'Content-Type: application/json' -d "$BODY" > "$out"
    kill $pid 2>/dev/null; pkill -P $pid 2>/dev/null; wait $pid 2>/dev/null
    return 0
}

tokens_of() { python3 -c "import json;d=json.load(open('$1'));print(' '.join(map(str,(d.get('tokens') or [])[:16])))"; }

port_run() { # file out extra...
    local f=$1 out=$2; shift 2
    bash parity/limited.sh -- $PORT -m "$f" -p "$P" -n 16 -t 8 "$@" 2>$OUT/port.err > "$out" || {
        echo "PORT RUN FAILED: $f $*" | tee -a $OUT/errors; fail=1; return 1; }
}

# the driver commits whole verify rounds, so the CLI may print n_predict+1
# tokens (speculative-simple.cpp:281) — the comparison takes the first 16
port_tokens_of() { sed -n 's/^gen tokens: \[\(.*\)\]$/\1/p' "$1" | head -1 | tr -d ' ' | tr ',' '\n' | head -16 | tr '\n' ' ' | sed 's/ $//'; }

REF_OK="glm4moe cohere2moe hy_v3 mimo2 step35"
REF_ABORT="qwen35 qwen35moe qwen3next bailingmoe3"

for arch in $REF_OK $REF_ABORT; do
    MTP=/tmp/mtp2/$arch-synth-mtp.gguf
    [ -f "$MTP" ] || { echo "missing $MTP (run the mtp2_write_synth_files generator)" >&2; exit 1; }

    echo "=== $arch ==="
    case " $REF_ABORT " in
        *" $arch "*)
            # the reference's own trunk decode aborts — record it, then the
            # port self-consistency cell (plain == spec)
            if run_ref "$MTP" $OUT/$arch-ref-plain.log $OUT/$arch-ref-plain.json; then
                echo "  UNEXPECTED: the reference now trunk-decodes $arch — promote it to REF_OK"
                fail=1
            else
                echo "  ref trunk decode aborts (documented): $(grep -m1 -oE 'GGML_ASSERT\(.*\) failed' $OUT/$arch-ref-plain.log)"
            fi
            ;;
        *)
            run_ref "$MTP" $OUT/$arch-ref-plain.log $OUT/$arch-ref-plain.json || { echo "  REF PLAIN FAILED"; fail=1; continue; }
            run_ref "$MTP" $OUT/$arch-ref-spec.log  $OUT/$arch-ref-spec.json  -fa off --spec-type draft-mtp || { echo "  REF SPEC FAILED"; fail=1; continue; }
            ;;
    esac

    port_run "$MTP" $OUT/$arch-port-plain.txt || continue
    port_run "$MTP" $OUT/$arch-port-spec.txt -fa off --spec-type draft-mtp --spec-draft-n-max 3 || continue
    P_PLAIN=$(port_tokens_of $OUT/$arch-port-plain.txt)
    P_SPEC=$(port_tokens_of $OUT/$arch-port-spec.txt)
    PORT_DR=$(grep -o "spec: n_drafted = [0-9]*" $OUT/$arch-port-spec.txt | grep -o '[0-9]*')
    PORT_AC=$(grep -o "spec: n_accept  = [0-9]*" $OUT/$arch-port-spec.txt | grep -o '[0-9]*')

    # the driver commits whole verify rounds and the synthetic heads accept
    # nothing, so both streams are pure target greedy — except qwen35's
    # documented step-13 flip on THIS (tokenized) prompt: the port's multi-row
    # verify GEMM is row-shape-sensitive (mtp2_e2e's mtp2_qwen35_rowcount_probe
    # measures max|1row-4row| ~= 2e-2 on identical state) and the plain top-2
    # margin at that step sits inside the band. n_max=0 is exact, a second
    # prompt is 16/16, the in-repo cell is 16/16 — the deepseek4 precedent of
    # parity/mtp_parity.sh.
    n_same=$(python3 -c "
a = '$P_PLAIN'.split(); b = '$P_SPEC'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
    need=16
    [ "$arch" = qwen35 ] && need=13
    if [ "$n_same" -ge "$need" ]; then
        echo "  port self-consistency: $n_same/16 identical (need >= $need)"
        echo "  port counters: drafted $PORT_DR, accepted $PORT_AC"
    else
        echo "  port self-consistency FAIL ($n_same/16 < $need)"
        echo "    plain: $P_PLAIN"
        echo "    spec : $P_SPEC"
        fail=1
    fi

    if [ -f $OUT/$arch-ref-spec.json ]; then
        T_PLAIN=$(tokens_of $OUT/$arch-ref-plain.json)
        T_SPEC=$(tokens_of $OUT/$arch-ref-spec.json)
        REF_ACC=$(grep -oE "draft acceptance = [0-9.]+ \([ ]*[0-9]+ accepted / *[0-9]+ generated\), mean len = +[0-9.]+" \
            $OUT/$arch-ref-spec.log | tail -1)
        n_ref_ps=$(python3 -c "
a = '$T_PLAIN'.split(); b = '$T_SPEC'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
        n_ref_port=$(python3 -c "
a = '$T_SPEC'.split(); b = '$P_PLAIN'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
        if [ "$n_ref_ps" -ge 16 ] && [ "$n_ref_port" -ge "$need" ] && [ "$(echo $T_SPEC | wc -w)" -ge 16 ]; then
            echo "  stream parity: ref plain == ref spec (16/16), ref spec == port ($n_ref_port/16, need >= $need) PASS"
            echo "  ref  : $REF_ACC"
        else
            echo "  stream parity FAIL"
            echo "    ref plain : $T_PLAIN"
            echo "    ref spec  : $T_SPEC"
            echo "    port plain: $P_PLAIN"
            echo "    port spec : $P_SPEC"
            echo "    ref  acc  : $REF_ACC"
            fail=1
        fi
    fi
done

echo
if [ $fail -eq 0 ]; then
    echo "MTP2 PARITY: ALL CELLS PASS"
else
    echo "MTP2 PARITY: FAILURES (see above)"
fi
exit $fail
