#!/usr/bin/env bash
# qwen4exp_mtp_parity.sh — the qwen4exp MTP driver-level parity, the mtp2_parity.sh
# protocol applied to the batch-42f head:
#   cell (a) stream parity: ref plain == ref spec == port plain == port spec
#     (16 greedy tokens) over the synthetic qwen4exp nextn GGUF;
#   cell (b) the bit-level chain dumps (gen_glm5_mtp_ref.sh — 12 steps,
#     logits + h_nextn rows byte-for-byte).
#
# The reference side runs a fresh llama-server's FIRST /completion
# (temperature 0, cache_prompt=false) with -fa off --spec-type draft-mtp —
# the MTP draft context is the hybrid-idx one of llama-model.cpp:2501-2508
# (nextn-only attn+idx filters, empty recurrent half — exactly what
# b9acf138a's llama_memory_recurrent partial-seq_rm tolerance is for).
#
# usage: ./parity/limited.sh -- bash parity/qwen4exp_mtp_parity.sh   (the synth
# is generated by gen_glm5_mtp_ref.sh / the glm5_mtp test generator)
set -u

REF=/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin/llama-server
PORT=$(dirname "$0")/../target/release/llama-cli
OUT=/tmp/qwen4exp-mtp-parity
mkdir -p $OUT

P='1, 2, 3, 4, 5, 6'
BODY='{"prompt":"'$P'","n_predict":16,"temperature":0,"cache_prompt":false,"return_tokens":true}'

PORT_BASE=${PORT_BASE:-18910}   # fresh port per run, incremented

fail=0

run_ref() { # file log outjson extra...
    local f=$1 log=$2 out=$3; shift 3
    local port=$PORT_BASE; PORT_BASE=$((PORT_BASE + 1))
    bash "$(dirname "$0")"/limited.sh -- \
        $REF -m "$f" -c 512 -t 8 --port $port --host 127.0.0.1 "$@" > "$log" 2>&1 &
    local pid=$!
    local ok=""
    for _ in $(seq 1 240); do
        curl -sf "http://127.0.0.1:$port/health" > /dev/null 2>&1 && { ok=1; break; }
        kill -0 $pid 2>/dev/null || break
        sleep 0.5
    done
    if [ -z "$ok" ]; then
        kill $pid 2>/dev/null; pkill -P $pid 2>/dev/null; wait $pid 2>/dev/null
        return 1
    fi
    curl -s "http://127.0.0.1:$port/completion" -H 'Content-Type: application/json' -d "$BODY" > "$out"
    kill $pid 2>/dev/null; pkill -P $pid 2>/dev/null; wait $pid 2>/dev/null
    return 0
}

tokens_of() { python3 -c "import json;d=json.load(open('$1'));print(' '.join(map(str,(d.get('tokens') or [])[:16])))"; }

port_run() { # file out extra...
    local f=$1 out=$2; shift 2
    bash "$(dirname "$0")"/limited.sh -- $PORT -m "$f" -p "$P" -n 16 -t 8 "$@" 2>$OUT/port.err > "$out" || {
        echo "PORT RUN FAILED: $f $*" | tee -a $OUT/errors; fail=1; return 1; }
}

# the driver commits whole verify rounds, so the CLI may print n_predict+1
# tokens — the comparison takes the first 16
port_tokens_of() { sed -n 's/^gen tokens: \[\(.*\)\]$/\1/p' "$1" | head -1 | tr -d ' ' | tr ',' '\n' | head -16 | tr '\n' ' ' | sed 's/ $//'; }

MTP=/tmp/mtp2/qwen4exp-synth-mtp.gguf
[ -f "$MTP" ] || { echo "missing $MTP (run parity/gen_qwen4exp_mtp_ref.sh or the glm5_mtp generator)" >&2; exit 1; }

echo "=== qwen4exp (draft-mtp) ==="
if run_ref "$MTP" $OUT/ref-plain.log $OUT/ref-plain.json; then
    echo "  ref plain ok"
else
    echo "  ref trunk decode failed: $(grep -m1 -oE '(GGML_ASSERT\(.*\) failed|error: .*)' $OUT/ref-plain.log)"
    fail=1
fi
if run_ref "$MTP" $OUT/ref-spec.log $OUT/ref-spec.json -fa off --spec-type draft-mtp; then
    echo "  ref spec ok"
else
    echo "  ref spec failed: $(grep -m1 -oE '(GGML_ASSERT\(.*\) failed|error: .*)' $OUT/ref-spec.log)"
    fail=1
fi

port_run "$MTP" $OUT/port-plain.txt || exit 1
port_run "$MTP" $OUT/port-spec.txt -fa off --spec-type draft-mtp --spec-draft-n-max 3 || exit 1
P_PLAIN=$(port_tokens_of $OUT/port-plain.txt)
P_SPEC=$(port_tokens_of $OUT/port-spec.txt)
PORT_DR=$(grep -o "spec: n_drafted = [0-9]*" $OUT/port-spec.txt | grep -o '[0-9]*')
PORT_AC=$(grep -o "spec: n_accept  = [0-9]*" $OUT/port-spec.txt | grep -o '[0-9]*')

n_same=$(python3 -c "
a = '$P_PLAIN'.split(); b = '$P_SPEC'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
if [ "$n_same" -ge 16 ]; then
    echo "  port self-consistency: $n_same/16 identical"
    echo "  port counters: drafted $PORT_DR, accepted $PORT_AC"
else
    echo "  port self-consistency FAIL ($n_same/16)"
    echo "    plain: $P_PLAIN"
    echo "    spec : $P_SPEC"
    fail=1
fi

if [ -f $OUT/ref-spec.json ]; then
    T_PLAIN=$(tokens_of $OUT/ref-plain.json)
    T_SPEC=$(tokens_of $OUT/ref-spec.json)
    REF_ACC=$(grep -oE "draft acceptance = [0-9.]+ \([ ]*[0-9]+ accepted / *[0-9]+ generated\), mean len = +[0-9.]+" \
        $OUT/ref-spec.log | tail -1)
    n_ref_ps=$(python3 -c "
a = '$T_PLAIN'.split(); b = '$T_SPEC'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
    n_ref_port=$(python3 -c "
a = '$T_SPEC'.split(); b = '$P_PLAIN'.split()
print(sum(1 for x, y in zip(a, b) if x == y))")
    if [ "$n_ref_ps" -ge 16 ] && [ "$n_ref_port" -ge 16 ] && [ "$(echo $T_SPEC | wc -w)" -ge 16 ]; then
        echo "  stream parity: ref plain == ref spec (16/16), ref spec == port ($n_ref_port/16) PASS"
        echo "  ref  : $REF_ACC"
    else
        echo "  stream parity FAIL"
        echo "    ref plain : $T_PLAIN"
        echo "    ref spec  : $T_SPEC"
        echo "    port plain: $P_PLAIN"
        echo "    port spec : $P_SPEC"
        echo "    ref  acc  : $REF_ACC"
        fail=1
    fi
fi

if [ $fail -eq 0 ]; then
    echo "QWEN4EXP MTP PARITY: ALL CELLS PASS"
else
    echo "QWEN4EXP MTP PARITY: FAILURES (see above)"
fi
exit $fail
