/* ref_interp_dump.c — kernel ground truth for GGML_OP_UPSCALE as the vision
 * graph uses it (clip.cpp:327 `ggml_interpolate(..., BILINEAR|ALIGN_CORNERS)`).
 *
 * It reproduces the exact node chain of `clip_graph::resize_position_embeddings`
 * for an image whose patch grid is 28x28 against a 48x48 learned grid:
 *
 *     pos  [1152, 2304]  (the mmproj's v.position_embd.weight layout)
 *     a = reshape_3d(pos, 1152, 48, 48)
 *     b = permute(a, 2, 0, 1, 3)                  -> [48, 48, 1152]
 *     c = ggml_interpolate(b, 28, 28, 1152, 1, GGML_SCALE_MODE_BILINEAR | GGML_SCALE_FLAG_ALIGN_CORNERS)
 *     d = permute(c, 1, 2, 0, 3)                  -> [1152, 28, 28]
 *     e = cont_2d(d, 1152, 784)
 *
 * The input values are generated by a fixed formula so the Rust side can
 * reproduce them bit for bit (no RNG, no libm).
 *
 * Build (from the repo root):
 *   PINNED=/home/jeffrey/llm/llama.cpp-pinned
 *   REF=/home/jeffrey/llm/llama.cpp/build-rust-ref/bin
 *   gcc -O2 -std=c11 parity/ref_interp_dump.c -I$PINNED/ggml/include \
 *       -o parity/ref_interp_dump -L$REF -lggml -lggml-cpu -lggml-base -lm \
 *       -Wl,-rpath,$REF
 * Run: ./parity/ref_interp_dump parity/interp_ref.bin
 *
 * File format: [i64 ne0][i64 ne1][i64 ne2][i64 ne3][f32 data...] (little endian),
 * the four dims being the cont_2d result.
 */
#include "ggml.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define N_EMBD 1152
#define N_SIDE 48
#define OUT_SIDE 28

static float gen(float * dst, size_t n) {
    for (size_t i = 0; i < n; ++i) {
        // deterministic, exactly representable values
        dst[i] = ((float) ((i * 37) % 2048) - 1024.0f) / 512.0f;
    }
    return 0.0f;
}

int main(int argc, char ** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <out.bin>\n", argv[0]);
        return 1;
    }

    struct ggml_init_params params = {
        /*.mem_size   =*/ 64 * 1024 * 1024,
        /*.mem_buffer =*/ NULL,
        /*.no_alloc   =*/ false,
    };
    struct ggml_context * ctx = ggml_init(params);

    struct ggml_tensor * pos = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, N_EMBD, N_SIDE * N_SIDE);
    gen((float *) pos->data, (size_t) N_EMBD * N_SIDE * N_SIDE);

    struct ggml_tensor * a = ggml_reshape_3d(ctx, pos, N_EMBD, N_SIDE, N_SIDE);
    struct ggml_tensor * b = ggml_permute(ctx, a, 2, 0, 1, 3);
    struct ggml_tensor * c = ggml_interpolate(ctx, b, OUT_SIDE, OUT_SIDE, N_EMBD, 1,
            GGML_SCALE_MODE_BILINEAR | GGML_SCALE_FLAG_ALIGN_CORNERS);
    struct ggml_tensor * d = ggml_permute(ctx, c, 1, 2, 0, 3);
    struct ggml_tensor * e = ggml_cont_2d(ctx, d, N_EMBD, OUT_SIDE * OUT_SIDE);

    struct ggml_cgraph * gf = ggml_new_graph(ctx);
    ggml_build_forward_expand(gf, e);
    ggml_graph_compute_with_ctx(ctx, gf, 8);

    int64_t hdr[4];
    ggml_graph_compute_with_ctx(ctx, gf, 1); // second run: determinism check

    FILE * f = fopen(argv[1], "wb");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }
    hdr[0] = e->ne[0];
    hdr[1] = e->ne[1];
    hdr[2] = e->ne[2];
    hdr[3] = e->ne[3];
    fwrite(hdr, sizeof(hdr), 1, f);
    fwrite(e->data, sizeof(float), (size_t) ggml_nelements(e), f);
    fclose(f);

    double sum = 0.0;
    const float * p = (const float *) e->data;
    for (int64_t i = 0; i < ggml_nelements(e); ++i) {
        sum += p[i];
    }
    printf("ref_interp_dump: ne = [%lld %lld %lld %lld], sum = %.6f\n",
           (long long) e->ne[0], (long long) e->ne[1], (long long) e->ne[2], (long long) e->ne[3], sum);

    ggml_free(ctx);
    return 0;
}