#!/usr/bin/env bash
# systemone_parity.sh — `/v1/systemone` e2e vs the NEW reference server
# (a7b94df2c), the tools/server lane of sync batch C2.
#
# The upstream unit test (tools/server/tests/unit/test_systemone.py) uses two
# HF-hosted tiny decision models; this box is offline, so the fixture is a
# SYNTHETIC laya model generated by
# crates/tools/llama-server/tests/systemone_parity.rs (`gen`, ignored):
# a 2-layer bert + `bert.decision.type = laya` + fitted temperatures + the
# `systemone` chat template. Both servers load the SAME file, so the answers
# must agree (float tolerance for the bert forward's ~1e-6 band).
#
# checks (mirroring the python test's shape):
#   1. the 3-question request: status 200, answer structure, probabilities
#      agreeing with the reference, choice == argmax, sums == 1, noul in
#      [0,1], usage.output_tokens == 0
#   2. invalid-request matrix -> 400 on both sides
#   3. images -> 501 on both sides (no mmproj wired)
set -uo pipefail
cd "$(dirname "$0")/.."

REF="${REF:-/home/jeffrey/llm/llama.cpp-next/build-rust-ref/bin/llama-server}"
PORT_BIN="${PORT_BIN:-./target/release/llama-server}"
MODEL="${MODEL:-/tmp/s2t-laya/tinylaya-synth.gguf}"
OUT=/tmp/s2t-laya
PORT_REF=8912
PORT_RUST=8913
mkdir -p "$OUT"

# 1. regenerate the fixture if missing
if [ ! -f "$MODEL" ]; then
    echo "== generating the synthetic tinylaya fixture =="
    parity/limited.sh -- cargo test --release -p llama-server --test systemone_parity gen -- --ignored --nocapture
fi

free -g | awk 'NR==2{print "  (mem available: "$7"G)"}'

cleanup() {
    [ -n "${REF_PID:-}" ] && kill "$REF_PID" 2>/dev/null
    [ -n "${RUST_PID:-}" ] && kill "$RUST_PID" 2>/dev/null
}
trap cleanup EXIT

# 2. both servers on the same file
parity/limited.sh -- "$REF" -m "$MODEL" -c 512 -t 4 --port $PORT_REF --host 127.0.0.1 >"$OUT/ref.log" 2>&1 &
REF_PID=$!
parity/limited.sh -- "$PORT_BIN" -m "$MODEL" -c 512 -t 4 --port $PORT_RUST --host 127.0.0.1 >"$OUT/port.log" 2>&1 &
RUST_PID=$!

for i in $(seq 1 60); do
    ok1=$(curl -s --max-time 2 "http://127.0.0.1:$PORT_REF/health" | grep -c '"ok"' || true)
    ok2=$(curl -s --max-time 2 "http://127.0.0.1:$PORT_RUST/health" | grep -c '"ok"' || true)
    [ "$ok1" = "1" ] && [ "$ok2" = "1" ] && break
    sleep 1
done
echo "both servers up (ref pid $REF_PID, port pid $RUST_PID)"

PASS=0; FAIL=0
check() { if [ "$1" = "0" ]; then echo "MATCH  $2"; PASS=$((PASS+1)); else echo "DIFF   $2"; FAIL=$((FAIL+1)); fi }

post() { # port path body out -> http code
    parity/limited.sh -- curl -s --max-time 120 -X POST "http://127.0.0.1:$1$2" -d "$3" -o "$4" -w '%{http_code}'
}

cat >"$OUT/req.json" <<'EOF'
{"state": "I was charged twice for my order last week and nobody has replied.", "questions": {
  "route": {"type": "choice", "instructions": "Which team should handle this?", "criteria": {"billing": "payments and refunds", "shipping": null, "technical": null}},
  "urgency": {"type": "score", "instructions": "How urgent is this?", "criteria": ["can wait", "this week", "today", "right now"]},
  "angry": {"type": "noul", "instructions": "Is the customer angry?"}
}}
EOF

# ---- check 1: the 3-question request --------------------------------------
s_ref=$(post $PORT_REF /v1/systemone @"$OUT/req.json" "$OUT/ref-ans.json")
s_port=$(post $PORT_RUST /v1/systemone @"$OUT/req.json" "$OUT/port-ans.json")
[ "$s_ref" = "200" ] && [ "$s_port" = "200" ]; check $? "3-question request 200 (ref $s_ref / port $s_port)"

parity/limited.sh -- python3 - "$OUT" <<'EOF'
import json, sys
out = sys.argv[1]
a = json.load(open(f"{out}/ref-ans.json"))
b = json.load(open(f"{out}/port-ans.json"))
ok = True
def fail(msg):
    global ok; ok = False; print("  DIFF:", msg)

# usage identical (input_tokens must match exactly — same tokens)
if a["usage"] != b["usage"]:
    fail(f"usage {a['usage']} vs {b['usage']}")
if a["usage"]["output_tokens"] != 0:
    fail("output_tokens != 0")

for qid in a["answers"]:
    qa, qb = a["answers"][qid], b["answers"][qid]
    if qa["type"] != qb["type"]:
        fail(f"{qid}.type"); continue
    if "noul" in qa:
        if abs(qa["noul"] - qb["noul"]) > 1e-4:
            fail(f"{qid}.noul {qa['noul']} vs {qb['noul']}")
        if not (0.0 <= qb["noul"] <= 1.0):
            fail(f"{qid}.noul out of [0,1]")
        continue
    pa, pb = qa["probabilities"], qb["probabilities"]
    if list(pa.keys()) != list(pb.keys()):
        fail(f"{qid}.probabilities keys {list(pa)} vs {list(pb)}")
    s = 0.0
    for k in pa:
        if abs(pa[k] - pb[k]) > 1e-4:
            fail(f"{qid}.probabilities[{k}] {pa[k]} vs {pb[k]}")
        s += pb[k]
    if abs(s - 1.0) > 1e-4:
        fail(f"{qid}.probabilities sum {s}")
    best = max(pb, key=pb.get)
    if qb.get("choice") is not None and qb["choice"] != best:
        fail(f"{qid}.choice {qb['choice']} != argmax {best}")
    if not (0.0 <= qb["confidence"] <= 1.0):
        fail(f"{qid}.confidence out of [0,1]")
    if "score" in qa:
        exp = sum(int(k) * v for k, v in pb.items())
        if abs(qb["score"] - exp) > 1e-4:
            fail(f"{qid}.score {qb['score']} != expectation {exp}")

sys.exit(0 if ok else 1)
EOF
check $? "3-question answers vs reference (float tol 1e-4)"

# ---- check 2: the invalid-request matrix (both 400) -----------------------
i=0
while IFS= read -r body; do
    i=$((i+1))
    s1=$(post $PORT_REF /v1/systemone "$body" "$OUT/ref-bad$i.json")
    s2=$(post $PORT_RUST /v1/systemone "$body" "$OUT/port-bad$i.json")
    [ "$s1" = "400" ] && [ "$s2" = "400" ]; check $? "invalid request #$i -> 400 (ref $s1 / port $s2)"
done <<'BODIES'
{"questions": {"route": {"type": "noul", "instructions": "x"}}}
{"state": "s"}
{"state": "s", "questions": {}}
{"state": "s", "questions": {"q": {"type": "unknown", "instructions": "x"}}}
{"state": "s", "questions": {"q": {"type": "noul"}}}
{"state": "s", "questions": {"q": {"type": "choice", "instructions": "x"}}}
{"state": "s", "questions": {"q": {"type": "choice", "instructions": "x", "criteria": {}}}}
{"state": "s", "questions": {"q": {"type": "score", "instructions": "x", "criteria": ["only one"]}}}
BODIES

# ---- check 3: images -> 501 (no mmproj wired) ------------------------------
img='data:image/png;base64,iVBORw0KGgo='
s1=$(post $PORT_REF /v1/systemone "{\"state\": \"s\", \"images\": [\"$img\"], \"questions\": {\"q\": {\"type\": \"noul\", \"instructions\": \"x\"}}}" "$OUT/ref-img.json")
s2=$(post $PORT_RUST /v1/systemone "{\"state\": \"s\", \"images\": [\"$img\"], \"questions\": {\"q\": {\"type\": \"noul\", \"instructions\": \"x\"}}}" "$OUT/port-img.json")
# the reference answers 501 for a laya model (can_use_images() false)
[ "$s1" = "501" ] && [ "$s2" = "501" ]; check $? "images -> 501 (ref $s1 / port $s2)"

# non-data-URL images are a 400 on both sides
s1=$(post $PORT_REF /v1/systemone '{"state": "s", "images": ["https://example.com/image.png"], "questions": {"q": {"type": "noul", "instructions": "x"}}}' "$OUT/ref-img2.json")
s2=$(post $PORT_RUST /v1/systemone '{"state": "s", "images": ["https://example.com/image.png"], "questions": {"q": {"type": "noul", "instructions": "x"}}}' "$OUT/port-img2.json")
[ "$s1" = "400" ] && [ "$s2" = "400" ]; check $? "non-data-URL image -> 400 (ref $s1 / port $s2)"

echo
echo "systemone parity: $PASS MATCH, $FAIL DIFF (of $((PASS+FAIL)))"
[ "$FAIL" = "0" ]
